"""
Seed Module 04 — Training Loops & Optimization (20 exercises).
Usage: python -m seeds.questions_training_loops
"""

import asyncio

from seeds.loader import build_exercise, seed_questions_for_topic

TOPIC_SLUG = "training-loops"

_SPECS: list[tuple] = [
    ("Training step order", "training-step-order", "basic", "Complete one SGD step: zero_grad, forward, loss, backward, step.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2, 1)\nopt = optim.SGD(m.parameters(), lr=0.1)\nx, y = torch.randn(4, 2), torch.randn(4, 1)\nloss_fn = nn.MSELoss()\n# YOUR CODE: one training step\nprint('step done')", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2, 1)\nopt = optim.SGD(m.parameters(), lr=0.1)\nx, y = torch.randn(4, 2), torch.randn(4, 1)\nloss_fn = nn.MSELoss()\nopt.zero_grad()\nloss = loss_fn(m(x), y)\nloss.backward()\nopt.step()\nprint('step done')", ["training", "loop"], "code_completion"),
    ("Adam optimizer step", "adam-optimizer-step", "basic", "Use `optim.Adam` on a linear model and run one update.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(3, 2)\nopt = # YOUR CODE\nloss = m(torch.randn(2,3)).sum()\n# one step\nprint('ok')", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(3, 2)\nopt = optim.Adam(m.parameters(), lr=1e-3)\nloss = m(torch.randn(2,3)).sum()\nopt.zero_grad()\nloss.backward()\nopt.step()\nprint('ok')", ["training", "adam"], "code_completion"),
    ("Set model train mode", "model-train-mode", "basic", "Call `model.train()` and print `model.training`.", "import torch\nfrom torch import nn\nmodel = nn.Linear(4, 2)\n# YOUR CODE\nprint(model.training)", "import torch\nfrom torch import nn\nmodel = nn.Linear(4, 2)\nmodel.train()\nprint(model.training)", ["training", "mode"], "code_completion"),
    ("Set model eval mode", "model-eval-mode", "basic", "Call `model.eval()` and print `model.training`.", "import torch\nfrom torch import nn\nmodel = nn.Linear(4, 2)\nmodel.train()\n# YOUR CODE\nprint(model.training)", "import torch\nfrom torch import nn\nmodel = nn.Linear(4, 2)\nmodel.train()\nmodel.eval()\nprint(model.training)", ["training", "mode"], "code_completion"),
    ("Epoch loop skeleton", "epoch-loop-skeleton", "basic", "Loop 3 epochs over a list of 2 fake batches; print epoch index.", "import torch\nbatches = [(torch.randn(2,3), torch.randn(2,1)) for _ in range(2)]\nfor epoch in range(3):\n    # YOUR CODE: print epoch\n    pass", "import torch\nbatches = [(torch.randn(2,3), torch.randn(2,1)) for _ in range(2)]\nfor epoch in range(3):\n    print('epoch', epoch)\n    for x, y in batches:\n        pass", ["training", "epoch"], "code_completion"),
    ("SGD with momentum", "sgd-momentum", "basic", "Create `SGD(..., momentum=0.9)` and print momentum value.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2, 1)\nopt = # YOUR CODE\nprint(opt.param_groups[0]['momentum'])", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2, 1)\nopt = optim.SGD(m.parameters(), lr=0.01, momentum=0.9)\nprint(opt.param_groups[0]['momentum'])", ["training", "sgd"], "code_completion"),
    ("Learning rate value", "read-learning-rate", "basic", "Print initial learning rate from Adam param group.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2, 2)\nopt = optim.Adam(m.parameters(), lr=0.05)\nprint(opt.param_groups[0]['lr'])", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2, 2)\nopt = optim.Adam(m.parameters(), lr=0.05)\nprint(opt.param_groups[0]['lr'])", ["training", "lr"], "code_completion"),
    ("Freeze backbone train head", "freeze-backbone", "basic", "Freeze first layer params, train only last layer.", "import torch\nfrom torch import nn\nmodel = nn.Sequential(nn.Linear(4,8), nn.ReLU(), nn.Linear(8,2))\n# freeze first layer\nfor p in model[0].parameters():\n    p.requires_grad = False\nprint(model[0].weight.requires_grad, model[2].weight.requires_grad)", "import torch\nfrom torch import nn\nmodel = nn.Sequential(nn.Linear(4,8), nn.ReLU(), nn.Linear(8,2))\nfor p in model[0].parameters():\n    p.requires_grad = False\nprint(model[0].weight.requires_grad, model[2].weight.requires_grad)", ["training", "finetune"], "code_completion"),
    ("StepLR scheduler", "steplr-scheduler", "intermediate", "Use `StepLR(optimizer, step_size=2, gamma=0.5)`; step twice and print lr.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2,1)\nopt = optim.SGD(m.parameters(), lr=0.1)\nsched = # YOUR CODE\nsched.step(); sched.step()\nprint(opt.param_groups[0]['lr'])", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2,1)\nopt = optim.SGD(m.parameters(), lr=0.1)\nsched = optim.lr_scheduler.StepLR(opt, step_size=2, gamma=0.5)\nsched.step(); sched.step()\nprint(opt.param_groups[0]['lr'])", ["training", "scheduler"], "code_completion"),
    ("ReduceLROnPlateau", "reduce-lr-on-plateau", "intermediate", "Step scheduler with metric 0.5 then 0.2; print lr after second step.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2,1)\nopt = optim.SGD(m.parameters(), lr=0.1)\nsched = optim.lr_scheduler.ReduceLROnPlateau(opt, patience=1)\nsched.step(0.5)\nsched.step(0.2)\nprint(opt.param_groups[0]['lr'])", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2,1)\nopt = optim.SGD(m.parameters(), lr=0.1)\nsched = optim.lr_scheduler.ReduceLROnPlateau(opt, patience=1)\nsched.step(0.5)\nsched.step(0.2)\nprint(opt.param_groups[0]['lr'])", ["training", "scheduler"], "code_completion"),
    ("Clip grads in loop", "clip-grad-in-loop", "intermediate", "Backward then `clip_grad_norm_(model.parameters(), 1.0)`.", "import torch\nfrom torch import nn\nm = nn.Linear(10, 1)\nx = torch.randn(4, 10)\nloss = m(x).sum()\nloss.backward()\n# clip here\ntotal = torch.nn.utils.clip_grad_norm_(m.parameters(), 1.0)\nprint(float(total))", "import torch\nfrom torch import nn\nm = nn.Linear(10, 1)\nx = torch.randn(4, 10)\nloss = m(x).sum()\nloss.backward()\ntotal = torch.nn.utils.clip_grad_norm_(m.parameters(), 1.0)\nprint(float(total))", ["training", "clipping"], "code_completion"),
    ("Weight decay in AdamW", "adamw-weight-decay", "intermediate", "Create AdamW with weight_decay=0.01 and print param group.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(3, 2)\nopt = optim.AdamW(m.parameters(), lr=1e-3, weight_decay=0.01)\nprint(opt.param_groups[0]['weight_decay'])", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(3, 2)\nopt = optim.AdamW(m.parameters(), lr=1e-3, weight_decay=0.01)\nprint(opt.param_groups[0]['weight_decay'])", ["training", "regularization"], "code_completion"),
    ("CosineAnnealingLR", "cosine-annealing-lr", "intermediate", "Run CosineAnnealingLR for T_max=4 steps; print lr.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2,1)\nopt = optim.SGD(m.parameters(), lr=0.2)\nsched = optim.lr_scheduler.CosineAnnealingLR(opt, T_max=4)\nfor _ in range(4):\n    sched.step()\nprint(round(opt.param_groups[0]['lr'], 4))", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2,1)\nopt = optim.SGD(m.parameters(), lr=0.2)\nsched = optim.lr_scheduler.CosineAnnealingLR(opt, T_max=4)\nfor _ in range(4):\n    sched.step()\nprint(round(opt.param_groups[0]['lr'], 4))", ["training", "scheduler"], "code_completion"),
    ("Gradient accumulation", "gradient-accumulation", "intermediate", "Accumulate 4 mini-batches; call optimizer.step once per 4.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nmodel = nn.Linear(4, 1)\nopt = optim.SGD(model.parameters(), lr=0.01)\ncriterion = nn.MSELoss()\nbatches = [(torch.randn(4,4), torch.randn(4,1)) for _ in range(8)]\naccumulation_steps = 4\nopt.zero_grad()\nfor i, (x, y) in enumerate(batches):\n    loss = criterion(model(x), y) / accumulation_steps\n    loss.backward()\n    if (i + 1) % accumulation_steps == 0:\n        opt.step()\n        opt.zero_grad()\nprint('done')", "import torch\nfrom torch import nn\nimport torch.optim as optim\nmodel = nn.Linear(4, 1)\nopt = optim.SGD(model.parameters(), lr=0.01)\ncriterion = nn.MSELoss()\nbatches = [(torch.randn(4,4), torch.randn(4,1)) for _ in range(8)]\naccumulation_steps = 4\nopt.zero_grad()\nfor i, (x, y) in enumerate(batches):\n    loss = criterion(model(x), y) / accumulation_steps\n    loss.backward()\n    if (i + 1) % accumulation_steps == 0:\n        opt.step()\n        opt.zero_grad()\nprint('done')", ["training", "accumulation"], "build_from_scratch"),
    ("Mixed precision autocast", "mixed-precision-autocast", "advanced", "Run forward under `torch.autocast(device_type='cpu')`.", "import torch\nfrom torch import nn\nm = nn.Linear(4, 2)\nx = torch.randn(2, 4)\nwith torch.autocast(device_type='cpu'):\n    y = m(x)\nprint(y.dtype)", "import torch\nfrom torch import nn\nm = nn.Linear(4, 2)\nx = torch.randn(2, 4)\nwith torch.autocast(device_type='cpu'):\n    y = m(x)\nprint(y.dtype)", ["training", "amp"], "code_completion"),
    ("GradScaler step", "grad-scaler-step", "advanced", "Use GradScaler: scale loss, backward, step, update.", "import torch\nfrom torch import nn\nfrom torch.cuda.amp import GradScaler\nm = nn.Linear(3, 1)\nopt = torch.optim.SGD(m.parameters(), lr=0.01)\nscaler = GradScaler(enabled=False)\nx = torch.randn(2, 3)\nopt.zero_grad()\nwith torch.autocast(device_type='cpu'):\n    loss = m(x).sum()\nscaler.scale(loss).backward()\nscaler.step(opt)\nscaler.update()\nprint('scaled')", "import torch\nfrom torch import nn\nfrom torch.cuda.amp import GradScaler\nm = nn.Linear(3, 1)\nopt = torch.optim.SGD(m.parameters(), lr=0.01)\nscaler = GradScaler(enabled=False)\nx = torch.randn(2, 3)\nopt.zero_grad()\nwith torch.autocast(device_type='cpu'):\n    loss = m(x).sum()\nscaler.scale(loss).backward()\nscaler.step(opt)\nscaler.update()\nprint('scaled')", ["training", "amp"], "code_completion"),
    ("Custom training loop", "custom-training-loop", "advanced", "Implement 2-epoch loop with manual metric tracking.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nmodel = nn.Linear(2, 1)\nopt = optim.SGD(model.parameters(), lr=0.1)\ndata = [(torch.randn(3,2), torch.randn(3,1)) for _ in range(4)]\nfor epoch in range(2):\n    total = 0.0\n    for x, y in data:\n        opt.zero_grad()\n        loss = nn.MSELoss()(model(x), y)\n        loss.backward()\n        opt.step()\n        total += loss.item()\n    print(epoch, round(total, 3))", "import torch\nfrom torch import nn\nimport torch.optim as optim\nmodel = nn.Linear(2, 1)\nopt = optim.SGD(model.parameters(), lr=0.1)\ndata = [(torch.randn(3,2), torch.randn(3,1)) for _ in range(4)]\nfor epoch in range(2):\n    total = 0.0\n    for x, y in data:\n        opt.zero_grad()\n        loss = nn.MSELoss()(model(x), y)\n        loss.backward()\n        opt.step()\n        total += loss.item()\n    print(epoch, round(total, 3))", ["training", "loop"], "build_from_scratch"),
    ("Notebook training lab", "notebook-training-lab", "intermediate", "Complete this exercise in Colab: full training loop on synthetic regression data.", "import torch\n# Open in Colab to run GPU-ready training loop\nprint('Open in Colab')", "import torch\nprint('Open in Colab')", ["training", "colab"], "notebook_challenge"),
    ("Predict output shape after Linear", "predict-linear-output-shape", "basic", "Given `x` shape `(8, 16)` and `nn.Linear(16, 10)`, what is output shape? Print it.", "import torch\nfrom torch import nn\nx = torch.randn(8, 16)\nlayer = nn.Linear(16, 10)\nprint(layer(x).shape)", "import torch\nfrom torch import nn\nx = torch.randn(8, 16)\nlayer = nn.Linear(16, 10)\nprint(layer(x).shape)", ["training", "shape"], "shape_assertion", "(8, 10)"),
]

QUESTIONS = []
for spec in _SPECS:
    kwargs = {}
    if len(spec) == 9:
        title, slug, diff, task, starter, solution, tags, qtype, shape = spec
        kwargs["expected_output_shape"] = shape
    else:
        title, slug, diff, task, starter, solution, tags, qtype = spec
    QUESTIONS.append(
        build_exercise(
            title=title,
            slug=slug,
            difficulty=diff,
            task=task,
            starter_code=starter,
            solution_code=solution,
            tags=tags,
            question_type=qtype,
            **kwargs,
        )
    )


async def main() -> None:
    await seed_questions_for_topic(TOPIC_SLUG, QUESTIONS, "Module 04 — Training Loops")


if __name__ == "__main__":
    asyncio.run(main())
