"""
Seed Modules 08–13 — RNNs through PyTorch Lightning (20 exercises each).
Usage: python -m seeds.questions_modules_08_13
"""

import asyncio

from seeds.loader import build_exercise, seed_questions_for_topic

MODULE_SPECS: dict[str, list[tuple]] = {
    "rnns-lstms": [
        ("RNN output shape", "rnn-output-shape", "basic", "Run `nn.RNN(10, 20, batch_first=True)` on `(2, 5, 10)` and print output shape.", "import torch\nfrom torch import nn\nx = torch.randn(2, 5, 10)\nrnn = nn.RNN(10, 20, batch_first=True)\nout, h = rnn(x)\nprint(out.shape, h.shape)", "import torch\nfrom torch import nn\nx = torch.randn(2, 5, 10)\nrnn = nn.RNN(10, 20, batch_first=True)\nout, h = rnn(x)\nprint(out.shape, h.shape)", ["rnn", "shape"], "code_completion"),
        ("LSTM cell forward", "lstm-cell-forward", "basic", "Forward `(3, 4, 8)` through `nn.LSTM(8, 16, batch_first=True)`.", "import torch\nfrom torch import nn\nx = torch.randn(3, 4, 8)\nlstm = nn.LSTM(8, 16, batch_first=True)\nout, (h, c) = lstm(x)\nprint(out.shape)", "import torch\nfrom torch import nn\nx = torch.randn(3, 4, 8)\nlstm = nn.LSTM(8, 16, batch_first=True)\nout, (h, c) = lstm(x)\nprint(out.shape)", ["lstm", "forward"], "code_completion"),
        ("GRU hidden state", "gru-hidden-state", "basic", "Use `nn.GRU` and print final hidden shape.", "import torch\nfrom torch import nn\nx = torch.randn(2, 6, 12)\ngru = nn.GRU(12, 24, batch_first=True)\n_, h = gru(x)\nprint(h.shape)", "import torch\nfrom torch import nn\nx = torch.randn(2, 6, 12)\ngru = nn.GRU(12, 24, batch_first=True)\n_, h = gru(x)\nprint(h.shape)", ["gru", "hidden"], "code_completion"),
        ("Bidirectional RNN", "bidirectional-rnn", "basic", "Bidirectional LSTM doubles hidden dim — print `out.shape[-1]`.", "import torch\nfrom torch import nn\nx = torch.randn(2, 5, 8)\nlstm = nn.LSTM(8, 16, batch_first=True, bidirectional=True)\nout, _ = lstm(x)\nprint(out.shape[-1])", "import torch\nfrom torch import nn\nx = torch.randn(2, 5, 8)\nlstm = nn.LSTM(8, 16, batch_first=True, bidirectional=True)\nout, _ = lstm(x)\nprint(out.shape[-1])", ["rnn", "bidirectional"], "code_completion"),
        ("Sequence lengths tensor", "sequence-lengths-tensor", "basic", "Create `lengths = torch.tensor([5, 3, 4])` for batch size 3.", "import torch\nlengths = # YOUR CODE\nprint(lengths)", "import torch\nlengths = torch.tensor([5, 3, 4])\nprint(lengths)", ["rnn", "padding"], "code_completion"),
        ("pack_padded_sequence", "pack-padded-sequence", "intermediate", "Pack variable-length sequences with `pack_padded_sequence`.", "import torch\nfrom torch.nn.utils.rnn import pack_padded_sequence\nx = torch.randn(3, 5, 8)\nlengths = torch.tensor([5, 3, 2])\npacked = pack_padded_sequence(x, lengths, batch_first=True, enforce_sorted=False)\nprint(packed.data.shape)", "import torch\nfrom torch.nn.utils.rnn import pack_padded_sequence\nx = torch.randn(3, 5, 8)\nlengths = torch.tensor([5, 3, 2])\npacked = pack_padded_sequence(x, lengths, batch_first=True, enforce_sorted=False)\nprint(packed.data.shape)", ["rnn", "pack"], "code_completion"),
        ("pad_packed_sequence", "pad-packed-sequence", "intermediate", "Unpack RNN output back to padded tensor.", "import torch\nfrom torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence\nfrom torch import nn\nx = torch.randn(2, 4, 6)\nlengths = torch.tensor([4, 2])\nrnn = nn.GRU(6, 10, batch_first=True)\npacked = pack_padded_sequence(x, lengths, batch_first=True, enforce_sorted=False)\nout_packed, _ = rnn(packed)\nout, _ = pad_packed_sequence(out_packed, batch_first=True)\nprint(out.shape)", "import torch\nfrom torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence\nfrom torch import nn\nx = torch.randn(2, 4, 6)\nlengths = torch.tensor([4, 2])\nrnn = nn.GRU(6, 10, batch_first=True)\npacked = pack_padded_sequence(x, lengths, batch_first=True, enforce_sorted=False)\nout_packed, _ = rnn(packed)\nout, _ = pad_packed_sequence(out_packed, batch_first=True)\nprint(out.shape)", ["rnn", "pad"], "code_completion"),
        ("Many-to-one classifier", "many-to-one-classifier", "intermediate", "Use last timestep output for classification head.", "import torch\nfrom torch import nn\nx = torch.randn(4, 7, 16)\nlstm = nn.LSTM(16, 32, batch_first=True)\nclassifier = nn.Linear(32, 5)\nout, _ = lstm(x)\nlogits = classifier(out[:, -1, :])\nprint(logits.shape)", "import torch\nfrom torch import nn\nx = torch.randn(4, 7, 16)\nlstm = nn.LSTM(16, 32, batch_first=True)\nclassifier = nn.Linear(32, 5)\nout, _ = lstm(x)\nlogits = classifier(out[:, -1, :])\nprint(logits.shape)", ["rnn", "classifier"], "code_completion"),
        ("Seq2Seq encoder", "seq2seq-encoder", "intermediate", "Encoder LSTM returns context vector for decoder.", "import torch\nfrom torch import nn\nsrc = torch.randn(2, 6, 12)\nenc = nn.LSTM(12, 24, batch_first=True)\n_, (h, c) = enc(src)\nprint(h.shape)", "import torch\nfrom torch import nn\nsrc = torch.randn(2, 6, 12)\nenc = nn.LSTM(12, 24, batch_first=True)\n_, (h, c) = enc(src)\nprint(h.shape)", ["rnn", "seq2seq"], "code_completion"),
        ("Attention context vector", "attention-context-vector", "advanced", "Compute dot-product attention scores over encoder outputs.", "import torch\nimport torch.nn.functional as F\ndec_h = torch.randn(2, 1, 24)\nenc_out = torch.randn(2, 6, 24)\nscores = torch.bmm(dec_h, enc_out.transpose(1, 2))\nweights = F.softmax(scores, dim=-1)\ncontext = torch.bmm(weights, enc_out)\nprint(context.shape)", "import torch\nimport torch.nn.functional as F\ndec_h = torch.randn(2, 1, 24)\nenc_out = torch.randn(2, 6, 24)\nscores = torch.bmm(dec_h, enc_out.transpose(1, 2))\nweights = F.softmax(scores, dim=-1)\ncontext = torch.bmm(weights, enc_out)\nprint(context.shape)", ["rnn", "attention"], "code_completion"),
        ("Teacher forcing flag", "teacher-forcing-flag", "intermediate", "Simulate teacher forcing by mixing gold vs predicted inputs.", "import torch\np = 0.5\nuse_teacher = torch.rand(1).item() < p\nprint(use_teacher)", "import torch\np = 0.5\nuse_teacher = torch.rand(1).item() < p\nprint(use_teacher)", ["rnn", "training"], "code_completion"),
        ("RNN dropout", "rnn-dropout", "basic", "Create LSTM with `dropout=0.2` when num_layers > 1.", "import torch\nfrom torch import nn\nlstm = nn.LSTM(8, 16, num_layers=2, dropout=0.2, batch_first=True)\nprint(lstm.dropout)", "import torch\nfrom torch import nn\nlstm = nn.LSTM(8, 16, num_layers=2, dropout=0.2, batch_first=True)\nprint(lstm.dropout)", ["rnn", "dropout"], "code_completion"),
        ("Stacked RNN layers", "stacked-rnn-layers", "basic", "3-layer GRU with `num_layers=3`; print number of layers.", "import torch\nfrom torch import nn\ngru = nn.GRU(10, 20, num_layers=3, batch_first=True)\nprint(gru.num_layers)", "import torch\nfrom torch import nn\ngru = nn.GRU(10, 20, num_layers=3, batch_first=True)\nprint(gru.num_layers)", ["rnn", "layers"], "code_completion"),
        ("CTC loss shape", "ctc-loss-shape", "advanced", "Print output shape from `nn.CTCLoss` log-probs `(T, N, C)`.", "import torch\nT, N, C = 50, 16, 28\nlog_probs = torch.randn(T, N, C).log_softmax(2)\ntargets = torch.randint(1, C, (N, 30))\ninput_lengths = torch.full((N,), T)\ntarget_lengths = torch.randint(10, 30, (N,))\nloss = torch.nn.CTCLoss()(log_probs, targets, input_lengths, target_lengths)\nprint(loss.shape)", "import torch\nT, N, C = 50, 16, 28\nlog_probs = torch.randn(T, N, C).log_softmax(2)\ntargets = torch.randint(1, C, (N, 30))\ninput_lengths = torch.full((N,), T)\ntarget_lengths = torch.randint(10, 30, (N,))\nloss = torch.nn.CTCLoss()(log_probs, targets, input_lengths, target_lengths)\nprint(loss.shape)", ["rnn", "ctc"], "code_completion"),
        ("TCN dilated conv", "tcn-dilated-conv", "advanced", "Dilated Conv1d with dilation=2 on sequence `(N, C, L)`.", "import torch\nfrom torch import nn\nx = torch.randn(2, 8, 32)\nconv = nn.Conv1d(8, 8, kernel_size=3, padding=2, dilation=2)\nprint(conv(x).shape)", "import torch\nfrom torch import nn\nx = torch.randn(2, 8, 32)\nconv = nn.Conv1d(8, 8, kernel_size=3, padding=2, dilation=2)\nprint(conv(x).shape)", ["rnn", "tcn"], "code_completion"),
        ("Notebook RNN lab", "notebook-rnn-lab", "intermediate", "Train a char-level RNN in Colab.", "import torch\nprint('Open in Colab')", "import torch\nprint('Open in Colab')", ["rnn", "colab"], "notebook_challenge"),
        ("Build SeqClassifier", "build-seq-classifier", "advanced", "Implement `SeqClassifier` with LSTM + linear head.", "import torch\nfrom torch import nn\nclass SeqClassifier(nn.Module):\n    def __init__(self):\n        super().__init__()\n        pass\n    def forward(self, x):\n        pass\nprint(SeqClassifier()(torch.randn(2,5,8)).shape)", "import torch\nfrom torch import nn\nclass SeqClassifier(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.lstm = nn.LSTM(8, 32, batch_first=True)\n        self.fc = nn.Linear(32, 4)\n    def forward(self, x):\n        out, _ = self.lstm(x)\n        return self.fc(out[:, -1])\nprint(SeqClassifier()(torch.randn(2,5,8)).shape)", ["rnn", "build"], "build_from_scratch"),
        ("Debug RNN hidden mismatch", "debug-rnn-hidden", "intermediate", "Fix bidirectional LSTM head input size (32 not 16).", "import torch\nfrom torch import nn\nlstm = nn.LSTM(8, 16, batch_first=True, bidirectional=True)\nhead = nn.Linear(16, 5)  # BUG\nx = torch.randn(2, 4, 8)\nout, _ = lstm(x)\nprint(head(out[:, -1]).shape)", "import torch\nfrom torch import nn\nlstm = nn.LSTM(8, 16, batch_first=True, bidirectional=True)\nhead = nn.Linear(32, 5)\nx = torch.randn(2, 4, 8)\nout, _ = lstm(x)\nprint(head(out[:, -1]).shape)", ["rnn", "debug"], "debug_model"),
        ("LSTM output shape assertion", "lstm-output-shape-assertion", "basic", "LSTM(8→16) on `(2,5,8)` — output shape?", "import torch\nfrom torch import nn\nx = torch.randn(2, 5, 8)\nprint(nn.LSTM(8, 16, batch_first=True)(x)[0].shape)", "import torch\nfrom torch import nn\nx = torch.randn(2, 5, 8)\nprint(nn.LSTM(8, 16, batch_first=True)(x)[0].shape)", ["rnn", "shape"], "shape_assertion", "(2, 5, 16)"),
        ("Conceptual: vanishing gradients", "conceptual-vanishing-gradients", "basic", "Why do vanilla RNNs struggle with long sequences? (print answer key)", "answer = 'Vanishing gradients limit long-term credit assignment'\nprint(answer)", "answer = 'Vanishing gradients limit long-term credit assignment'\nprint(answer)", ["rnn", "theory"], "conceptual_mcq"),
    ],
    "transformers-attention": [
        ("Scaled dot-product attention", "scaled-dot-product-attention", "basic", "Compute attention scores `QK^T / sqrt(d_k)` for Q,K shape `(2,4,8)`.", "import torch\nimport math\nQ = K = torch.randn(2, 4, 8)\nscores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(8)\nprint(scores.shape)", "import torch\nimport math\nQ = K = torch.randn(2, 4, 8)\nscores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(8)\nprint(scores.shape)", ["transformer", "attention"], "code_completion"),
        ("Softmax attention weights", "softmax-attention-weights", "basic", "Apply softmax on last dim of scores.", "import torch\nimport torch.nn.functional as F\nscores = torch.randn(2, 4, 4)\nweights = F.softmax(scores, dim=-1)\nprint(weights.sum(dim=-1)[0, 0])", "import torch\nimport torch.nn.functional as F\nscores = torch.randn(2, 4, 4)\nweights = F.softmax(scores, dim=-1)\nprint(weights.sum(dim=-1)[0, 0])", ["transformer", "attention"], "code_completion"),
        ("MultiheadAttention module", "multihead-attention-module", "basic", "Use `nn.MultiheadAttention(embed_dim=64, num_heads=8)` on seq len 10.", "import torch\nfrom torch import nn\nmha = nn.MultiheadAttention(64, 8, batch_first=True)\nx = torch.randn(2, 10, 64)\nout, _ = mha(x, x, x)\nprint(out.shape)", "import torch\nfrom torch import nn\nmha = nn.MultiheadAttention(64, 8, batch_first=True)\nx = torch.randn(2, 10, 64)\nout, _ = mha(x, x, x)\nprint(out.shape)", ["transformer", "mha"], "code_completion"),
        ("Sinusoidal positional encoding", "sinusoidal-positional-encoding", "basic", "Build PE for positions 0..9, dim 16; print PE shape.", "import torch\nimport math\npos = torch.arange(10).unsqueeze(1)\ni = torch.arange(0, 16, 2)\npe = torch.zeros(10, 16)\npe[:, 0::2] = torch.sin(pos / 10000 ** (i / 16))\npe[:, 1::2] = torch.cos(pos / 10000 ** (i / 16))\nprint(pe.shape)", "import torch\nimport math\npos = torch.arange(10).unsqueeze(1)\ni = torch.arange(0, 16, 2)\npe = torch.zeros(10, 16)\npe[:, 0::2] = torch.sin(pos / 10000 ** (i / 16))\npe[:, 1::2] = torch.cos(pos / 10000 ** (i / 16))\nprint(pe.shape)", ["transformer", "pe"], "code_completion"),
        ("Causal attention mask", "causal-attention-mask", "intermediate", "Create upper-triangular mask for autoregressive attention.", "import torch\nseq = 6\nmask = torch.triu(torch.ones(seq, seq), diagonal=1).bool()\nprint(mask[0].sum())", "import torch\nseq = 6\nmask = torch.triu(torch.ones(seq, seq), diagonal=1).bool()\nprint(mask[0].sum())", ["transformer", "mask"], "code_completion"),
        ("Padding mask", "padding-mask", "intermediate", "Mask padded tokens in batch using `key_padding_mask`.", "import torch\nfrom torch import nn\nmha = nn.MultiheadAttention(32, 4, batch_first=True)\nx = torch.randn(2, 5, 32)\nmask = torch.tensor([[False]*3 + [True]*2, [False]*5])\nout, _ = mha(x, x, x, key_padding_mask=mask)\nprint(out.shape)", "import torch\nfrom torch import nn\nmha = nn.MultiheadAttention(32, 4, batch_first=True)\nx = torch.randn(2, 5, 32)\nmask = torch.tensor([[False]*3 + [True]*2, [False]*5])\nout, _ = mha(x, x, x, key_padding_mask=mask)\nprint(out.shape)", ["transformer", "mask"], "code_completion"),
        ("TransformerEncoderLayer", "transformer-encoder-layer", "intermediate", "Forward through one `TransformerEncoderLayer`.", "import torch\nfrom torch import nn\nlayer = nn.TransformerEncoderLayer(d_model=64, nhead=8, batch_first=True)\nx = torch.randn(2, 12, 64)\nprint(layer(x).shape)", "import torch\nfrom torch import nn\nlayer = nn.TransformerEncoderLayer(d_model=64, nhead=8, batch_first=True)\nx = torch.randn(2, 12, 64)\nprint(layer(x).shape)", ["transformer", "encoder"], "code_completion"),
        ("TransformerEncoder stack", "transformer-encoder-stack", "intermediate", "Stack 4 encoder layers with `TransformerEncoder`.", "import torch\nfrom torch import nn\nlayer = nn.TransformerEncoderLayer(d_model=32, nhead=4, batch_first=True)\nenc = nn.TransformerEncoder(layer, num_layers=4)\nprint(enc(torch.randn(2, 8, 32)).shape)", "import torch\nfrom torch import nn\nlayer = nn.TransformerEncoderLayer(d_model=32, nhead=4, batch_first=True)\nenc = nn.TransformerEncoder(layer, num_layers=4)\nprint(enc(torch.randn(2, 8, 32)).shape)", ["transformer", "encoder"], "code_completion"),
        ("LayerNorm in transformer", "layernorm-in-transformer", "basic", "Apply `nn.LayerNorm(64)` on token embeddings.", "import torch\nfrom torch import nn\nx = torch.randn(2, 10, 64)\nprint(nn.LayerNorm(64)(x).shape)", "import torch\nfrom torch import nn\nx = torch.randn(2, 10, 64)\nprint(nn.LayerNorm(64)(x).shape)", ["transformer", "norm"], "code_completion"),
        ("Feed-forward block", "feed-forward-block", "basic", "FFN: Linear→GELU→Linear on `(B,T,64)`.", "import torch\nfrom torch import nn\nff = nn.Sequential(nn.Linear(64, 256), nn.GELU(), nn.Linear(256, 64))\nprint(ff(torch.randn(2, 10, 64)).shape)", "import torch\nfrom torch import nn\nff = nn.Sequential(nn.Linear(64, 256), nn.GELU(), nn.Linear(256, 64))\nprint(ff(torch.randn(2, 10, 64)).shape)", ["transformer", "ffn"], "code_completion"),
        ("RoPE concept", "rope-concept", "advanced", "Rotate Q/K pairs (simplified 2D rotation) for position 3.", "import torch\nimport math\ntheta = 3 / 10000 ** (0 / 2)\nc, s = math.cos(theta), math.sin(theta)\nq = torch.tensor([1.0, 0.0])\nrot = torch.tensor([[c, -s], [s, c]])\nprint((rot @ q).shape)", "import torch\nimport math\ntheta = 3 / 10000 ** (0 / 2)\nc, s = math.cos(theta), math.sin(theta)\nq = torch.tensor([1.0, 0.0])\nrot = torch.tensor([[c, -s], [s, c]])\nprint((rot @ q).shape)", ["transformer", "rope"], "code_completion"),
        ("KV-cache step", "kv-cache-step", "advanced", "Append new K,V to cache tensors along seq dim.", "import torch\nK_cache = torch.randn(2, 4, 8, 64)\nK_new = torch.randn(2, 1, 8, 64)\nK_cache = torch.cat([K_cache, K_new], dim=1)\nprint(K_cache.shape)", "import torch\nK_cache = torch.randn(2, 4, 8, 64)\nK_new = torch.randn(2, 1, 8, 64)\nK_cache = torch.cat([K_cache, K_new], dim=1)\nprint(K_cache.shape)", ["transformer", "cache"], "code_completion"),
        ("Grouped query attention", "grouped-query-attention", "advanced", "Repeat K,V heads to match Q head count (GQA pattern).", "import torch\nQ = torch.randn(2, 8, 32, 64)\nK = torch.randn(2, 8, 4, 64)\nK = K.repeat_interleave(8, dim=2)\nprint(Q.shape, K.shape)", "import torch\nQ = torch.randn(2, 8, 32, 64)\nK = torch.randn(2, 8, 4, 64)\nK = K.repeat_interleave(8, dim=2)\nprint(Q.shape, K.shape)", ["transformer", "gqa"], "code_completion"),
        ("Notebook transformer lab", "notebook-transformer-lab", "intermediate", "Implement mini GPT block in Colab.", "import torch\nprint('Open in Colab')", "import torch\nprint('Open in Colab')", ["transformer", "colab"], "notebook_challenge"),
        ("Build attention block", "build-attention-block", "advanced", "Implement single-head attention function.", "import torch\nimport math\ndef attention(Q, K, V):\n    pass\nQ=K=V=torch.randn(2,5,8)\nprint(attention(Q,K,V).shape)", "import torch\nimport math\ndef attention(Q, K, V):\n    scores = (Q @ K.transpose(-2,-1)) / math.sqrt(Q.size(-1))\n    w = torch.softmax(scores, dim=-1)\n    return w @ V\nQ=K=V=torch.randn(2,5,8)\nprint(attention(Q,K,V).shape)", ["transformer", "build"], "build_from_scratch"),
        ("Debug MHA embed dim", "debug-mha-embed-dim", "intermediate", "Fix MultiheadAttention embed_dim mismatch (must divide num_heads).", "import torch\nfrom torch import nn\nmha = nn.MultiheadAttention(60, 8, batch_first=True)  # BUG\nx = torch.randn(2, 6, 60)\nprint(mha(x,x,x)[0].shape)", "import torch\nfrom torch import nn\nmha = nn.MultiheadAttention(64, 8, batch_first=True)\nx = torch.randn(2, 6, 64)\nprint(mha(x,x,x)[0].shape)", ["transformer", "debug"], "debug_model"),
        ("MHA output shape", "mha-output-shape-assertion", "basic", "MHA preserves `(B,T,D)` shape.", "import torch\nfrom torch import nn\nx = torch.randn(2, 7, 64)\nprint(nn.MultiheadAttention(64, 8, batch_first=True)(x,x,x)[0].shape)", "import torch\nfrom torch import nn\nx = torch.randn(2, 7, 64)\nprint(nn.MultiheadAttention(64, 8, batch_first=True)(x,x,x)[0].shape)", ["transformer", "shape"], "shape_assertion", "(2, 7, 64)"),
        ("Cross-attention", "cross-attention", "intermediate", "Decoder queries attend to encoder memory.", "import torch\nfrom torch import nn\nmha = nn.MultiheadAttention(32, 4, batch_first=True)\ndec = torch.randn(2, 5, 32)\nenc = torch.randn(2, 8, 32)\nout, _ = mha(dec, enc, enc)\nprint(out.shape)", "import torch\nfrom torch import nn\nmha = nn.MultiheadAttention(32, 4, batch_first=True)\ndec = torch.randn(2, 5, 32)\nenc = torch.randn(2, 8, 32)\nout, _ = mha(dec, enc, enc)\nprint(out.shape)", ["transformer", "cross"], "code_completion"),
        ("Flash attention note", "flash-attention-note", "advanced", "Print when to prefer memory-efficient attention kernels.", "print('Use flash-attn / SDPA when sequence length is large')", "print('Use flash-attn / SDPA when sequence length is large')", ["transformer", "perf"], "conceptual_mcq"),
        ("CLS token pooling", "cls-token-pooling", "basic", "Take first token embedding as sentence representation.", "import torch\nx = torch.randn(2, 11, 64)\ncls = x[:, 0, :]\nprint(cls.shape)", "import torch\nx = torch.randn(2, 11, 64)\ncls = x[:, 0, :]\nprint(cls.shape)", ["transformer", "pooling"], "code_completion"),
    ],
    "transfer-learning": [
        ("Load pretrained ResNet", "load-pretrained-resnet", "basic", "Load `resnet18` weights with `weights=ResNet18_Weights.DEFAULT`.", "from torchvision import models\nfrom torchvision.models import ResNet18_Weights\nm = models.resnet18(weights=ResNet18_Weights.DEFAULT)\nprint(m.fc.in_features)", "from torchvision import models\nfrom torchvision.models import ResNet18_Weights\nm = models.resnet18(weights=ResNet18_Weights.DEFAULT)\nprint(m.fc.in_features)", ["transfer", "torchvision"], "code_completion"),
        ("Freeze backbone", "freeze-backbone-params", "basic", "Set `requires_grad=False` for all params except `fc`.", "from torchvision import models\nm = models.resnet18(weights=None)\nfor name, p in m.named_parameters():\n    p.requires_grad = name.startswith('fc')\nprint(sum(p.requires_grad for p in m.parameters()))", "from torchvision import models\nm = models.resnet18(weights=None)\nfor name, p in m.named_parameters():\n    p.requires_grad = name.startswith('fc')\nprint(sum(p.requires_grad for p in m.parameters()))", ["transfer", "freeze"], "code_completion"),
        ("Replace classifier head", "replace-classifier-head", "basic", "Replace ResNet `fc` for 10 classes.", "from torchvision import models\nimport torch.nn as nn\nm = models.resnet18(weights=None)\nm.fc = nn.Linear(m.fc.in_features, 10)\nprint(m.fc.out_features)", "from torchvision import models\nimport torch.nn as nn\nm = models.resnet18(weights=None)\nm.fc = nn.Linear(m.fc.in_features, 10)\nprint(m.fc.out_features)", ["transfer", "head"], "code_completion"),
        ("Feature extractor mode", "feature-extractor-mode", "basic", "Forward image through frozen backbone; print embedding shape.", "from torchvision import models\nimport torch\nm = models.resnet18(weights=None)\nm.eval()\nfor p in m.parameters():\n    p.requires_grad = False\nx = torch.randn(2, 3, 224, 224)\nwith torch.no_grad():\n    feats = m.conv1(x)  # simplified\nprint('eval mode', not m.training)", "from torchvision import models\nimport torch\nm = models.resnet18(weights=None)\nm.eval()\nfor p in m.parameters():\n    p.requires_grad = False\nx = torch.randn(2, 3, 224, 224)\nwith torch.no_grad():\n    pass\nprint('eval mode', not m.training)", ["transfer", "features"], "code_completion"),
        ("Discriminative LR", "discriminative-lr", "intermediate", "Two param groups: backbone lr=1e-5, head lr=1e-3.", "import torch\nfrom torchvision import models\nimport torch.optim as optim\nm = models.resnet18(weights=None)\nopt = optim.Adam([\n    {'params': m.fc.parameters(), 'lr': 1e-3},\n    {'params': [p for n,p in m.named_parameters() if not n.startswith('fc')], 'lr': 1e-5},\n])\nprint(len(opt.param_groups))", "import torch\nfrom torchvision import models\nimport torch.optim as optim\nm = models.resnet18(weights=None)\nopt = optim.Adam([\n    {'params': m.fc.parameters(), 'lr': 1e-3},\n    {'params': [p for n,p in m.named_parameters() if not n.startswith('fc')], 'lr': 1e-5},\n])\nprint(len(opt.param_groups))", ["transfer", "lr"], "code_completion"),
        ("Unfreeze last block", "unfreeze-last-block", "intermediate", "Unfreeze `layer4` only for fine-tuning.", "from torchvision import models\nm = models.resnet18(weights=None)\nfor n, p in m.named_parameters():\n    p.requires_grad = n.startswith('layer4') or n.startswith('fc')\nprint(sum(p.requires_grad for p in m.parameters()) > 0)", "from torchvision import models\nm = models.resnet18(weights=None)\nfor n, p in m.named_parameters():\n    p.requires_grad = n.startswith('layer4') or n.startswith('fc')\nprint(sum(p.requires_grad for p in m.parameters()) > 0)", ["transfer", "unfreeze"], "code_completion"),
        ("LoRA low-rank update", "lora-low-rank-update", "advanced", "Implement LoRA delta: `W + B@A` with rank 4.", "import torch\nW = torch.randn(64, 128)\nA = torch.randn(4, 128)\nB = torch.randn(64, 4)\nW_eff = W + B @ A\nprint(W_eff.shape)", "import torch\nW = torch.randn(64, 128)\nA = torch.randn(4, 128)\nB = torch.randn(64, 4)\nW_eff = W + B @ A\nprint(W_eff.shape)", ["transfer", "lora"], "code_completion"),
        ("Freeze BatchNorm stats", "freeze-bn-stats", "intermediate", "Keep BatchNorm in eval while training head.", "import torch\nfrom torch import nn\nm = nn.Sequential(nn.Linear(4, 8), nn.BatchNorm1d(8), nn.Linear(8, 2))\nm[1].eval()\nprint(m[1].training)", "import torch\nfrom torch import nn\nm = nn.Sequential(nn.Linear(4, 8), nn.BatchNorm1d(8), nn.Linear(8, 2))\nm[1].eval()\nprint(m[1].training)", ["transfer", "bn"], "code_completion"),
        ("Knowledge distillation loss", "knowledge-distillation-loss", "advanced", "KL between student and teacher logits with temperature.", "import torch\nimport torch.nn.functional as F\nT = 4.0\ns = torch.randn(2, 10)\nt = torch.randn(2, 10)\nloss = F.kl_div(F.log_softmax(s/T, 1), F.softmax(t/T, 1), reduction='batchmean') * (T*T)\nprint(loss.shape)", "import torch\nimport torch.nn.functional as F\nT = 4.0\ns = torch.randn(2, 10)\nt = torch.randn(2, 10)\nloss = F.kl_div(F.log_softmax(s/T, 1), F.softmax(t/T, 1), reduction='batchmean') * (T*T)\nprint(loss.shape)", ["transfer", "distill"], "code_completion"),
        ("PEFT adapter hook", "peft-adapter-hook", "advanced", "Register forward hook to capture intermediate activations.", "import torch\nfrom torch import nn\nacts = []\ndef hook(m, i, o):\n    acts.append(o)\nm = nn.Linear(8, 4)\nm.register_forward_hook(hook)\nm(torch.randn(2, 8))\nprint(len(acts))", "import torch\nfrom torch import nn\nacts = []\ndef hook(m, i, o):\n    acts.append(o)\nm = nn.Linear(8, 4)\nm.register_forward_hook(hook)\nm(torch.randn(2, 8))\nprint(len(acts))", ["transfer", "peft"], "code_completion"),
        ("Augment for fine-tune", "augment-for-finetune", "basic", "Apply RandomResizedCrop in torchvision transforms.", "from torchvision import transforms\nt = transforms.Compose([transforms.RandomResizedCrop(224), transforms.ToTensor()])\nprint(t)", "from torchvision import transforms\nt = transforms.Compose([transforms.RandomResizedCrop(224), transforms.ToTensor()])\nprint(t)", ["transfer", "augment"], "code_completion"),
        ("Save fine-tuned head only", "save-finetuned-head", "intermediate", "Save only `state_dict` keys starting with `fc`.", "from torchvision import models\nimport torch\nm = models.resnet18(weights=None)\nsd = {k: v for k, v in m.state_dict().items() if k.startswith('fc')}\nprint(len(sd))", "from torchvision import models\nimport torch\nm = models.resnet18(weights=None)\nsd = {k: v for k, v in m.state_dict().items() if k.startswith('fc')}\nprint(len(sd))", ["transfer", "checkpoint"], "code_completion"),
        ("Notebook transfer lab", "notebook-transfer-lab", "intermediate", "Fine-tune ResNet on custom dataset in Colab.", "import torch\nprint('Open in Colab')", "import torch\nprint('Open in Colab')", ["transfer", "colab"], "notebook_challenge"),
        ("Build linear probe", "build-linear-probe", "advanced", "Freeze features; train only `nn.Linear` probe.", "import torch\nfrom torch import nn\nclass Probe(nn.Module):\n    def __init__(self, d, c):\n        super().__init__()\n        self.fc = nn.Linear(d, c)\n    def forward(self, x):\n        return self.fc(x)\nprint(Probe(512, 10)(torch.randn(4, 512)).shape)", "import torch\nfrom torch import nn\nclass Probe(nn.Module):\n    def __init__(self, d, c):\n        super().__init__()\n        self.fc = nn.Linear(d, c)\n    def forward(self, x):\n        return self.fc(x)\nprint(Probe(512, 10)(torch.randn(4, 512)).shape)", ["transfer", "build"], "build_from_scratch"),
        ("Debug frozen head", "debug-frozen-head", "intermediate", "Head params must have requires_grad True.", "import torch\nfrom torch import nn\nhead = nn.Linear(10, 2)\nfor p in head.parameters():\n    p.requires_grad = False  # BUG\nprint(head.weight.requires_grad)", "import torch\nfrom torch import nn\nhead = nn.Linear(10, 2)\nfor p in head.parameters():\n    p.requires_grad = True\nprint(head.weight.requires_grad)", ["transfer", "debug"], "debug_model"),
        ("Probe output shape", "probe-output-shape", "basic", "Linear probe on 512-d features → 10 classes.", "import torch\nfrom torch import nn\nprint(nn.Linear(512, 10)(torch.randn(3, 512)).shape)", "import torch\nfrom torch import nn\nprint(nn.Linear(512, 10)(torch.randn(3, 512)).shape)", ["transfer", "shape"], "shape_assertion", "(3, 10)"),
        ("QLoRA concept", "qlora-concept", "advanced", "Why quantize base weights for LoRA fine-tuning?", "print('Reduce VRAM while adapting low-rank adapters')", "print('Reduce VRAM while adapting low-rank adapters')", ["transfer", "qlora"], "conceptual_mcq"),
        ("Timm model load", "timm-model-load", "intermediate", "Note: use timm.create_model for alternate backbones.", "print('pip install timm; timm.create_model(\"vit_base_patch16_224\", pretrained=True)')", "print('pip install timm; timm.create_model(\"vit_base_patch16_224\", pretrained=True)')", ["transfer", "timm"], "code_completion"),
        ("Early stopping metric", "early-stopping-metric", "intermediate", "Track validation loss; stop if no improvement.", "best = 1e9\ncur = 0.42\nimproved = cur < best\nprint(improved)", "best = 1e9\ncur = 0.42\nimproved = cur < best\nprint(improved)", ["transfer", "training"], "code_completion"),
    ],
    "model-deployment": [
        ("Save state_dict", "save-state-dict", "basic", "Save model weights with `torch.save(model.state_dict(), path)`.", "import torch\nfrom torch import nn\nimport tempfile\nm = nn.Linear(2, 1)\npath = tempfile.mktemp(suffix='.pt')\ntorch.save(m.state_dict(), path)\nprint('saved')", "import torch\nfrom torch import nn\nimport tempfile\nm = nn.Linear(2, 1)\npath = tempfile.mktemp(suffix='.pt')\ntorch.save(m.state_dict(), path)\nprint('saved')", ["deploy", "checkpoint"], "code_completion"),
        ("Load state_dict", "load-state-dict", "basic", "Load weights into a new model instance.", "import torch\nfrom torch import nn\nm1 = nn.Linear(3, 2)\nsd = m1.state_dict()\nm2 = nn.Linear(3, 2)\nm2.load_state_dict(sd)\nprint(torch.allclose(m1.weight, m2.weight))", "import torch\nfrom torch import nn\nm1 = nn.Linear(3, 2)\nsd = m1.state_dict()\nm2 = nn.Linear(3, 2)\nm2.load_state_dict(sd)\nprint(torch.allclose(m1.weight, m2.weight))", ["deploy", "checkpoint"], "code_completion"),
        ("Checkpoint dict", "checkpoint-dict", "intermediate", "Save epoch, model, optimizer in one checkpoint.", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2, 1)\nopt = optim.SGD(m.parameters(), lr=0.1)\nckpt = {'epoch': 3, 'model': m.state_dict(), 'optimizer': opt.state_dict()}\nprint(list(ckpt.keys()))", "import torch\nfrom torch import nn\nimport torch.optim as optim\nm = nn.Linear(2, 1)\nopt = optim.SGD(m.parameters(), lr=0.1)\nckpt = {'epoch': 3, 'model': m.state_dict(), 'optimizer': opt.state_dict()}\nprint(list(ckpt.keys()))", ["deploy", "checkpoint"], "code_completion"),
        ("TorchScript trace", "torchscript-trace", "intermediate", "Trace `nn.Linear` with example input.", "import torch\nfrom torch import nn\nm = nn.Linear(4, 2)\nm.eval()\ntsm = torch.jit.trace(m, torch.randn(1, 4))\nprint(tsm(torch.randn(2, 4)).shape)", "import torch\nfrom torch import nn\nm = nn.Linear(4, 2)\nm.eval()\ntsm = torch.jit.trace(m, torch.randn(1, 4))\nprint(tsm(torch.randn(2, 4)).shape)", ["deploy", "torchscript"], "code_completion"),
        ("TorchScript script", "torchscript-script", "intermediate", "Script a small function with `@torch.jit.script`.", "import torch\n@torch.jit.script\ndef relu2(x):\n    return torch.relu(x) * 2\nprint(relu2(torch.tensor([-1., 2.])))", "import torch\n@torch.jit.script\ndef relu2(x):\n    return torch.relu(x) * 2\nprint(relu2(torch.tensor([-1., 2.])))", ["deploy", "torchscript"], "code_completion"),
        ("ONNX export", "onnx-export", "intermediate", "Export linear model to ONNX (opset 17).", "import torch\nfrom torch import nn\nimport tempfile\nm = nn.Linear(3, 2)\nm.eval()\nx = torch.randn(1, 3)\npath = tempfile.mktemp(suffix='.onnx')\ntorch.onnx.export(m, x, path, input_names=['input'], output_names=['output'], opset_version=17)\nprint('exported')", "import torch\nfrom torch import nn\nimport tempfile\nm = nn.Linear(3, 2)\nm.eval()\nx = torch.randn(1, 3)\npath = tempfile.mktemp(suffix='.onnx')\ntorch.onnx.export(m, x, path, input_names=['input'], output_names=['output'], opset_version=17)\nprint('exported')", ["deploy", "onnx"], "code_completion"),
        ("torch.compile model", "torch-compile-model", "advanced", "Wrap model with `torch.compile` (PyTorch 2.x).", "import torch\nfrom torch import nn\nm = nn.Linear(8, 4)\ntry:\n    m = torch.compile(m)\n    print('compiled')\nexcept Exception as e:\n    print('skip', type(e).__name__)", "import torch\nfrom torch import nn\nm = nn.Linear(8, 4)\ntry:\n    m = torch.compile(m)\n    print('compiled')\nexcept Exception as e:\n    print('skip', type(e).__name__)", ["deploy", "compile"], "code_completion"),
        ("Inference no_grad", "inference-no-grad", "basic", "Run forward under `torch.inference_mode()`.", "import torch\nfrom torch import nn\nm = nn.Linear(2, 1)\nx = torch.randn(3, 2)\nwith torch.inference_mode():\n    y = m(x)\nprint(y.shape)", "import torch\nfrom torch import nn\nm = nn.Linear(2, 1)\nx = torch.randn(3, 2)\nwith torch.inference_mode():\n    y = m(x)\nprint(y.shape)", ["deploy", "inference"], "code_completion"),
        ("Model eval deploy", "model-eval-deploy", "basic", "Set eval before serving predictions.", "import torch\nfrom torch import nn\nm = nn.Linear(2, 1)\nm.train()\nm.eval()\nprint(m.training)", "import torch\nfrom torch import nn\nm = nn.Linear(2, 1)\nm.train()\nm.eval()\nprint(m.training)", ["deploy", "eval"], "code_completion"),
        ("Version metadata in ckpt", "version-metadata-ckpt", "intermediate", "Store `pytorch_version` string in checkpoint meta.", "import torch\nmeta = {'pytorch': torch.__version__, 'epoch': 1}\nprint(meta['pytorch'][:1])", "import torch\nmeta = {'pytorch': torch.__version__, 'epoch': 1}\nprint(meta['pytorch'][:1])", ["deploy", "meta"], "code_completion"),
        ("Half precision export", "half-precision-export", "intermediate", "Cast model to float16 for inference.", "import torch\nfrom torch import nn\nm = nn.Linear(4, 2).half()\nx = torch.randn(2, 4).half()\nprint(m(x).dtype)", "import torch\nfrom torch import nn\nm = nn.Linear(4, 2).half()\nx = torch.randn(2, 4).half()\nprint(m(x).dtype)", ["deploy", "fp16"], "code_completion"),
        ("Mobile lite interpreter", "mobile-lite-interpreter", "advanced", "Load TorchScript for mobile (conceptual).", "print('Use _save_for_lite_interpreter for mobile deployment')", "print('Use _save_for_lite_interpreter for mobile deployment')", ["deploy", "mobile"], "conceptual_mcq"),
        ("Notebook export lab", "notebook-export-lab", "intermediate", "Export trained model to ONNX in Colab.", "import torch\nprint('Open in Colab')", "import torch\nprint('Open in Colab')", ["deploy", "colab"], "notebook_challenge"),
        ("Build inference wrapper", "build-inference-wrapper", "advanced", "Class wrapping preprocess → model → softmax.", "import torch\nfrom torch import nn\nclass Infer(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.m = nn.Linear(4, 3)\n    def forward(self, x):\n        return torch.softmax(self.m(x), -1)\nprint(Infer()(torch.randn(2,4)).shape)", "import torch\nfrom torch import nn\nclass Infer(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.m = nn.Linear(4, 3)\n    def forward(self, x):\n        return torch.softmax(self.m(x), -1)\nprint(Infer()(torch.randn(2,4)).shape)", ["deploy", "build"], "build_from_scratch"),
        ("Debug strict load", "debug-strict-load", "intermediate", "Use `strict=False` when head shape changed.", "import torch\nfrom torch import nn\nm = nn.Linear(5, 2)\nsd = {'weight': torch.randn(2, 5), 'bias': torch.randn(2)}\nm.load_state_dict(sd, strict=True)\nprint('ok')", "import torch\nfrom torch import nn\nm = nn.Linear(5, 2)\nsd = {'weight': torch.randn(2, 5), 'bias': torch.randn(2)}\nm.load_state_dict(sd, strict=True)\nprint('ok')", ["deploy", "debug"], "debug_model"),
        ("Traced output shape", "traced-output-shape", "basic", "Traced Linear(4→2) on `(3,4)` output shape.", "import torch\nfrom torch import nn\nm = nn.Linear(4, 2)\nt = torch.jit.trace(m.eval(), torch.randn(1, 4))\nprint(t(torch.randn(3, 4)).shape)", "import torch\nfrom torch import nn\nm = nn.Linear(4, 2)\nt = torch.jit.trace(m.eval(), torch.randn(1, 4))\nprint(t(torch.randn(3, 4)).shape)", ["deploy", "shape"], "shape_assertion", "(3, 2)"),
        ("TensorRT note", "tensorrt-note", "advanced", "When to use TensorRT vs ONNX Runtime.", "print('TensorRT for NVIDIA serving; ONNX Runtime for cross-platform')", "print('TensorRT for NVIDIA serving; ONNX Runtime for cross-platform')", ["deploy", "tensorrt"], "conceptual_mcq"),
        ("Secure weights only", "secure-weights-only", "basic", "Never deploy pickled full model from untrusted source.", "print('Prefer state_dict over pickled nn.Module')", "print('Prefer state_dict over pickled nn.Module')", ["deploy", "security"], "conceptual_mcq"),
        ("Batch inference", "batch-inference", "intermediate", "Run batch of 8 through deployed model.", "import torch\nfrom torch import nn\nm = nn.Linear(6, 2).eval()\nprint(m(torch.randn(8, 6)).shape)", "import torch\nfrom torch import nn\nm = nn.Linear(6, 2).eval()\nprint(m(torch.randn(8, 6)).shape)", ["deploy", "batch"], "code_completion"),
    ],
    "gpu-cuda": [
        ("CUDA available check", "cuda-available-check", "basic", "Print whether CUDA is available.", "import torch\nprint(torch.cuda.is_available())", "import torch\nprint(torch.cuda.is_available())", ["gpu", "cuda"], "code_completion"),
        ("Tensor to device", "tensor-to-device", "basic", "Move tensor to `cuda` if available else cpu.", "import torch\ndevice = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\nx = torch.randn(2, 3).to(device)\nprint(x.device.type)", "import torch\ndevice = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\nx = torch.randn(2, 3).to(device)\nprint(x.device.type)", ["gpu", "device"], "code_completion"),
        ("Model to device", "model-to-device", "basic", "Move `nn.Linear` to selected device.", "import torch\nfrom torch import nn\ndevice = torch.device('cpu')\nm = nn.Linear(4, 2).to(device)\nprint(next(m.parameters()).device.type)", "import torch\nfrom torch import nn\ndevice = torch.device('cpu')\nm = nn.Linear(4, 2).to(device)\nprint(next(m.parameters()).device.type)", ["gpu", "device"], "code_completion"),
        ("Pin memory DataLoader", "pin-memory-dataloader", "intermediate", "Create DataLoader with `pin_memory=True`.", "import torch\nfrom torch.utils.data import DataLoader, TensorDataset\nx = torch.randn(20, 4)\ny = torch.randn(20, 1)\nloader = DataLoader(TensorDataset(x, y), batch_size=4, pin_memory=True)\nprint(loader.pin_memory)", "import torch\nfrom torch.utils.data import DataLoader, TensorDataset\nx = torch.randn(20, 4)\ny = torch.randn(20, 1)\nloader = DataLoader(TensorDataset(x, y), batch_size=4, pin_memory=True)\nprint(loader.pin_memory)", ["gpu", "dataloader"], "code_completion"),
        ("non_blocking transfer", "non-blocking-transfer", "intermediate", "Use `.to(device, non_blocking=True)` when pin_memory.", "import torch\ndevice = torch.device('cpu')\nx = torch.randn(4, 8)\nx = x.to(device, non_blocking=True)\nprint(x.device.type)", "import torch\ndevice = torch.device('cpu')\nx = torch.randn(4, 8)\nx = x.to(device, non_blocking=True)\nprint(x.device.type)", ["gpu", "transfer"], "code_completion"),
        ("Empty CUDA cache", "empty-cuda-cache", "basic", "Call `torch.cuda.empty_cache()` when CUDA available.", "import torch\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\nprint('done')", "import torch\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\nprint('done')", ["gpu", "memory"], "code_completion"),
        ("CUDA memory stats", "cuda-memory-stats", "intermediate", "Print allocated memory when CUDA available.", "import torch\nif torch.cuda.is_available():\n    print(torch.cuda.memory_allocated())\nelse:\n    print(0)", "import torch\nif torch.cuda.is_available():\n    print(torch.cuda.memory_allocated())\nelse:\n    print(0)", ["gpu", "memory"], "code_completion"),
        ("DataParallel wrap", "dataparallel-wrap", "intermediate", "Wrap model with `nn.DataParallel` when multi-GPU.", "import torch\nfrom torch import nn\nm = nn.Linear(4, 2)\nif torch.cuda.device_count() > 1:\n    m = nn.DataParallel(m)\nprint(type(m).__name__)", "import torch\nfrom torch import nn\nm = nn.Linear(4, 2)\nif torch.cuda.device_count() > 1:\n    m = nn.DataParallel(m)\nprint(type(m).__name__)", ["gpu", "parallel"], "code_completion"),
        ("DDP concept", "ddp-concept", "advanced", "Print why DistributedDataParallel beats DataParallel.", "print('DDP: one process per GPU, less GIL contention')", "print('DDP: one process per GPU, less GIL contention')", ["gpu", "ddp"], "conceptual_mcq"),
        ("torch.profiler context", "torch-profiler-context", "intermediate", "Run one step under profiler (CPU).", "import torch\nfrom torch import nn\nfrom torch.profiler import profile, ProfilerActivity\nm = nn.Linear(8, 4)\nx = torch.randn(2, 8)\nwith profile(activities=[ProfilerActivity.CPU]) as prof:\n    m(x)\nprint('profiled')", "import torch\nfrom torch import nn\nfrom torch.profiler import profile, ProfilerActivity\nm = nn.Linear(8, 4)\nx = torch.randn(2, 8)\nwith profile(activities=[ProfilerActivity.CPU]) as prof:\n    m(x)\nprint('profiled')", ["gpu", "profiler"], "code_completion"),
        ("Synchronize CUDA", "synchronize-cuda", "basic", "Call `torch.cuda.synchronize()` after GPU op when available.", "import torch\nif torch.cuda.is_available():\n    torch.cuda.synchronize()\nprint('sync')", "import torch\nif torch.cuda.is_available():\n    torch.cuda.synchronize()\nprint('sync')", ["gpu", "sync"], "code_completion"),
        ("Mixed device error", "mixed-device-error", "intermediate", "Fix: move both tensors to same device before add.", "import torch\na = torch.randn(2, 3)\nb = torch.randn(2, 3)\nprint((a + b).shape)", "import torch\na = torch.randn(2, 3)\nb = torch.randn(2, 3)\nprint((a + b).shape)", ["gpu", "debug"], "debug_model"),
        ("Gradient checkpointing", "gradient-checkpointing", "advanced", "Use `torch.utils.checkpoint.checkpoint` on block forward.", "import torch\nfrom torch import nn\nfrom torch.utils.checkpoint import checkpoint\nblock = nn.Sequential(nn.Linear(4, 4), nn.ReLU())\nx = torch.randn(2, 4, requires_grad=True)\ny = checkpoint(block, x)\nprint(y.shape)", "import torch\nfrom torch import nn\nfrom torch.utils.checkpoint import checkpoint\nblock = nn.Sequential(nn.Linear(4, 4), nn.ReLU())\nx = torch.randn(2, 4, requires_grad=True)\ny = checkpoint(block, x)\nprint(y.shape)", ["gpu", "checkpoint"], "code_completion"),
        ("FSDP concept", "fsdp-concept", "advanced", "When to use FullyShardedDataParallel.", "print('FSDP shards parameters across GPUs for large models')", "print('FSDP shards parameters across GPUs for large models')", ["gpu", "fsdp"], "conceptual_mcq"),
        ("Notebook GPU lab", "notebook-gpu-lab", "intermediate", "Profile GPU training step in Colab.", "import torch\nprint('Open in Colab')", "import torch\nprint('Open in Colab')", ["gpu", "colab"], "notebook_challenge"),
        ("Build device helper", "build-device-helper", "basic", "Function returning best available device.", "import torch\ndef get_device():\n    pass\nprint(get_device())", "import torch\ndef get_device():\n    return torch.device('cuda' if torch.cuda.is_available() else 'cpu')\nprint(get_device())", ["gpu", "build"], "build_from_scratch"),
        ("CUDA tensor shape", "cuda-tensor-shape", "basic", "Create tensor on CPU; print shape `(4, 5)`.", "import torch\nprint(torch.randn(4, 5).shape)", "import torch\nprint(torch.randn(4, 5).shape)", ["gpu", "shape"], "shape_assertion", "(4, 5)"),
        ("Streams concept", "streams-concept", "advanced", "CUDA streams enable async execution overlap.", "print('Use streams to overlap H2D copy with compute')", "print('Use streams to overlap H2D copy with compute')", ["gpu", "streams"], "conceptual_mcq"),
        ("Benchmark iter", "benchmark-iter", "intermediate", "Time 100 forward passes with `time.perf_counter`.", "import time\nimport torch\nfrom torch import nn\nm = nn.Linear(64, 32).eval()\nx = torch.randn(8, 64)\nt0 = time.perf_counter()\nfor _ in range(100):\n    m(x)\nprint(round(time.perf_counter() - t0, 4))", "import time\nimport torch\nfrom torch import nn\nm = nn.Linear(64, 32).eval()\nx = torch.randn(8, 64)\nt0 = time.perf_counter()\nfor _ in range(100):\n    m(x)\nprint(round(time.perf_counter() - t0, 4))", ["gpu", "benchmark"], "code_completion"),
        ("TF32 matmul flag", "tf32-matmul-flag", "advanced", "Enable TF32 on Ampere+ for faster matmul.", "import torch\nif hasattr(torch.backends, 'cuda'):\n    torch.backends.cuda.matmul.allow_tf32 = True\nprint('tf32')", "import torch\nif hasattr(torch.backends, 'cuda'):\n    torch.backends.cuda.matmul.allow_tf32 = True\nprint('tf32')", ["gpu", "perf"], "code_completion"),
        ("GPU required flag", "gpu-required-exercise", "advanced", "Mark exercise needing GPU — run in Colab if no CUDA.", "import torch\nprint('gpu_required:', torch.cuda.is_available())", "import torch\nprint('gpu_required:', torch.cuda.is_available())", ["gpu", "colab"], "code_completion", None, True),
    ],
    "pytorch-lightning": [
        ("LightningModule skeleton", "lightning-module-skeleton", "basic", "Subclass LightningModule with `training_step` stub.", "import pytorch_lightning as pl\nfrom torch import nn\nclass LitModel(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(4, 2)\n    def training_step(self, batch, batch_idx):\n        x, y = batch\n        loss = nn.MSELoss()(self.net(x), y)\n        self.log('train_loss', loss)\n        return loss\nprint(LitModel())", "import pytorch_lightning as pl\nfrom torch import nn\nclass LitModel(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(4, 2)\n    def training_step(self, batch, batch_idx):\n        x, y = batch\n        loss = nn.MSELoss()(self.net(x), y)\n        self.log('train_loss', loss)\n        return loss\nprint(LitModel())", ["lightning", "module"], "code_completion"),
        ("Configure optimizers", "configure-optimizers", "basic", "Return Adam optimizer from `configure_optimizers`.", "import pytorch_lightning as pl\nfrom torch import nn\nimport torch.optim as optim\nclass Lit(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(2, 1)\n    def training_step(self, b, i):\n        return self.net(b[0]).sum()\n    def configure_optimizers(self):\n        return optim.Adam(self.parameters(), lr=1e-3)\nprint(Lit().configure_optimizers())", "import pytorch_lightning as pl\nfrom torch import nn\nimport torch.optim as optim\nclass Lit(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(2, 1)\n    def training_step(self, b, i):\n        return self.net(b[0]).sum()\n    def configure_optimizers(self):\n        return optim.Adam(self.parameters(), lr=1e-3)\nprint(Lit().configure_optimizers())", ["lightning", "optim"], "code_completion"),
        ("Validation step", "validation-step", "basic", "Log `val_loss` in `validation_step`.", "import pytorch_lightning as pl\nfrom torch import nn\nclass Lit(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(2, 1)\n    def validation_step(self, batch, batch_idx):\n        x, y = batch\n        loss = nn.MSELoss()(self.net(x), y)\n        self.log('val_loss', loss)\nprint('ok')", "import pytorch_lightning as pl\nfrom torch import nn\nclass Lit(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(2, 1)\n    def validation_step(self, batch, batch_idx):\n        x, y = batch\n        loss = nn.MSELoss()(self.net(x), y)\n        self.log('val_loss', loss)\nprint('ok')", ["lightning", "val"], "code_completion"),
        ("LightningDataModule", "lightning-datamodule", "intermediate", "Implement `train_dataloader` returning DataLoader.", "import pytorch_lightning as pl\nfrom torch.utils.data import DataLoader, TensorDataset\nimport torch\nclass DM(pl.LightningDataModule):\n    def train_dataloader(self):\n        x = torch.randn(32, 4)\n        y = torch.randn(32, 1)\n        return DataLoader(TensorDataset(x, y), batch_size=8)\nprint(len(DM().train_dataloader()))", "import pytorch_lightning as pl\nfrom torch.utils.data import DataLoader, TensorDataset\nimport torch\nclass DM(pl.LightningDataModule):\n    def train_dataloader(self):\n        x = torch.randn(32, 4)\n        y = torch.randn(32, 1)\n        return DataLoader(TensorDataset(x, y), batch_size=8)\nprint(len(DM().train_dataloader()))", ["lightning", "data"], "code_completion"),
        ("Trainer max_epochs", "trainer-max-epochs", "basic", "Create `Trainer(max_epochs=3, accelerator='cpu')`.", "import pytorch_lightning as pl\ntrainer = pl.Trainer(max_epochs=3, accelerator='cpu', enable_checkpointing=False, logger=False)\nprint(trainer.max_epochs)", "import pytorch_lightning as pl\ntrainer = pl.Trainer(max_epochs=3, accelerator='cpu', enable_checkpointing=False, logger=False)\nprint(trainer.max_epochs)", ["lightning", "trainer"], "code_completion"),
        ("ModelCheckpoint callback", "model-checkpoint-callback", "intermediate", "Use `ModelCheckpoint(monitor='val_loss')`.", "import pytorch_lightning as pl\nfrom pytorch_lightning.callbacks import ModelCheckpoint\ncb = ModelCheckpoint(monitor='val_loss', mode='min')\nprint(cb.monitor)", "import pytorch_lightning as pl\nfrom pytorch_lightning.callbacks import ModelCheckpoint\ncb = ModelCheckpoint(monitor='val_loss', mode='min')\nprint(cb.monitor)", ["lightning", "callback"], "code_completion"),
        ("EarlyStopping callback", "early-stopping-callback", "intermediate", "EarlyStopping on `val_loss` patience=3.", "from pytorch_lightning.callbacks import EarlyStopping\nes = EarlyStopping(monitor='val_loss', patience=3)\nprint(es.patience)", "from pytorch_lightning.callbacks import EarlyStopping\nes = EarlyStopping(monitor='val_loss', patience=3)\nprint(es.patience)", ["lightning", "callback"], "code_completion"),
        ("LearningRateMonitor", "learning-rate-monitor", "basic", "Add LearningRateMonitor callback.", "from pytorch_lightning.callbacks import LearningRateMonitor\nm = LearningRateMonitor(logging_interval='epoch')\nprint(m.logging_interval)", "from pytorch_lightning.callbacks import LearningRateMonitor\nm = LearningRateMonitor(logging_interval='epoch')\nprint(m.logging_interval)", ["lightning", "callback"], "code_completion"),
        ("self.log metrics", "self-log-metrics", "basic", "Log train accuracy scalar in training_step.", "import pytorch_lightning as pl\nclass Lit(pl.LightningModule):\n    def training_step(self, batch, batch_idx):\n        self.log('acc', 0.9, on_step=True, on_epoch=True)\n        return 0.0\nprint(Lit())", "import pytorch_lightning as pl\nclass Lit(pl.LightningModule):\n    def training_step(self, batch, batch_idx):\n        self.log('acc', 0.9, on_step=True, on_epoch=True)\n        return 0.0\nprint(Lit())", ["lightning", "log"], "code_completion"),
        ("Predict step", "predict-step", "intermediate", "Implement `predict_step` returning logits.", "import pytorch_lightning as pl\nfrom torch import nn\nclass Lit(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(3, 2)\n    def predict_step(self, batch, batch_idx):\n        return self.net(batch)\nprint('predict')", "import pytorch_lightning as pl\nfrom torch import nn\nclass Lit(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(3, 2)\n    def predict_step(self, batch, batch_idx):\n        return self.net(batch)\nprint('predict')", ["lightning", "predict"], "code_completion"),
        ("Fabric API", "fabric-api", "advanced", "Create Fabric with `accelerator='cpu'`.", "from lightning.fabric import Fabric\nfabric = Fabric(accelerator='cpu')\nprint(fabric.device)", "from lightning.fabric import Fabric\nfabric = Fabric(accelerator='cpu')\nprint(fabric.device)", ["lightning", "fabric"], "code_completion"),
        ("DDP strategy trainer", "ddp-strategy-trainer", "advanced", "Trainer strategy `ddp` for multi-GPU (concept).", "import pytorch_lightning as pl\nprint(pl.strategies.DDPStrategy.__name__)", "import pytorch_lightning as pl\nprint(pl.strategies.DDPStrategy.__name__)", ["lightning", "ddp"], "conceptual_mcq"),
        ("W&B logger", "wandb-logger", "intermediate", "Note integrating WandbLogger (optional dep).", "print('from pytorch_lightning.loggers import WandbLogger')", "print('from pytorch_lightning.loggers import WandbLogger')", ["lightning", "logger"], "code_completion"),
        ("Notebook lightning lab", "notebook-lightning-lab", "intermediate", "Train LitModel with Trainer in Colab.", "import torch\nprint('Open in Colab')", "import torch\nprint('Open in Colab')", ["lightning", "colab"], "notebook_challenge"),
        ("Build minimal LitModule", "build-minimal-litmodule", "advanced", "Complete LitModule with forward + training_step.", "import pytorch_lightning as pl\nfrom torch import nn\nclass Lit(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        pass\nprint(Lit())", "import pytorch_lightning as pl\nfrom torch import nn\nclass Lit(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(4, 2)\n    def forward(self, x):\n        return self.net(x)\n    def training_step(self, batch, batch_idx):\n        x, y = batch\n        loss = nn.MSELoss()(self(x), y)\n        self.log('loss', loss)\n        return loss\nprint(Lit())", ["lightning", "build"], "build_from_scratch"),
        ("Debug log sync_dist", "debug-log-sync-dist", "intermediate", "Use `sync_dist=True` when logging on DDP.", "import pytorch_lightning as pl\nclass Lit(pl.LightningModule):\n    def training_step(self, b, i):\n        self.log('loss', 0.5, sync_dist=True)\n        return 0.5\nprint('sync')", "import pytorch_lightning as pl\nclass Lit(pl.LightningModule):\n    def training_step(self, b, i):\n        self.log('loss', 0.5, sync_dist=True)\n        return 0.5\nprint('sync')", ["lightning", "debug"], "debug_model"),
        ("Lit output shape", "lit-output-shape", "basic", "Linear layer in LitModule forward `(5,4)` → `(5,2)`.", "import torch\nfrom torch import nn\nprint(nn.Linear(4, 2)(torch.randn(5, 4)).shape)", "import torch\nfrom torch import nn\nprint(nn.Linear(4, 2)(torch.randn(5, 4)).shape)", ["lightning", "shape"], "shape_assertion", "(5, 2)"),
        ("Test step metric", "test-step-metric", "intermediate", "Implement `test_step` logging test_loss.", "import pytorch_lightning as pl\nfrom torch import nn\nclass Lit(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(2, 1)\n    def test_step(self, batch, batch_idx):\n        x, y = batch\n        self.log('test_loss', nn.MSELoss()(self.net(x), y))\nprint('test')", "import pytorch_lightning as pl\nfrom torch import nn\nclass Lit(pl.LightningModule):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Linear(2, 1)\n    def test_step(self, batch, batch_idx):\n        x, y = batch\n        self.log('test_loss', nn.MSELoss()(self.net(x), y))\nprint('test')", ["lightning", "test"], "code_completion"),
        ("Callbacks list", "callbacks-list", "basic", "Pass list of callbacks to Trainer.", "import pytorch_lightning as pl\nfrom pytorch_lightning.callbacks import ModelCheckpoint\ncallbacks = [ModelCheckpoint(save_top_k=1)]\ntrainer = pl.Trainer(max_epochs=1, callbacks=callbacks, accelerator='cpu', logger=False)\nprint(len(trainer.callbacks))", "import pytorch_lightning as pl\nfrom pytorch_lightning.callbacks import ModelCheckpoint\ncallbacks = [ModelCheckpoint(save_top_k=1)]\ntrainer = pl.Trainer(max_epochs=1, callbacks=callbacks, accelerator='cpu', logger=False)\nprint(len(trainer.callbacks))", ["lightning", "trainer"], "code_completion"),
        ("Best practices note", "lightning-best-practices", "basic", "Keep model logic in LightningModule, data in DataModule.", "print('Separation: LightningModule vs LightningDataModule')", "print('Separation: LightningModule vs LightningDataModule')", ["lightning", "practices"], "conceptual_mcq"),
    ],
}

LABELS = {
    "rnns-lstms": "Module 08 — RNNs & LSTMs",
    "transformers-attention": "Module 09 — Transformers",
    "transfer-learning": "Module 10 — Transfer Learning",
    "model-deployment": "Module 11 — Deployment",
    "gpu-cuda": "Module 12 — GPU & CUDA",
    "pytorch-lightning": "Module 13 — Lightning",
}


def _specs_to_questions(specs: list[tuple]) -> list[dict]:
    questions = []
    for spec in specs:
        kwargs: dict = {}
        if len(spec) == 9:
            title, slug, diff, task, starter, solution, tags, qtype, shape = spec
            kwargs["expected_output_shape"] = shape
        elif len(spec) == 10:
            title, slug, diff, task, starter, solution, tags, qtype, shape, gpu = spec
            kwargs["expected_output_shape"] = shape
            kwargs["gpu_required"] = gpu
        else:
            title, slug, diff, task, starter, solution, tags, qtype = spec
        questions.append(
            build_exercise(
                title=title,
                slug=slug,
                difficulty=diff,
                task=task,
                starter_code=starter,
                solution_code=solution,
                tags=tags,
                question_type=qtype,
                **kwargs,
            )
        )
    return questions


async def main() -> None:
    for slug, specs in MODULE_SPECS.items():
        await seed_questions_for_topic(slug, _specs_to_questions(specs), LABELS[slug])


if __name__ == "__main__":
    asyncio.run(main())
