"""
seeds/questions_python_modules_16_20.py
---------------------------------------
Python Learning Studio — Modules 16-20

Usage:
    python -m seeds.questions_python_modules_16_20
"""

import asyncio
from collections import Counter

from seeds.loader import seed_questions_for_topic


def _q(
    *,
    title: str,
    slug: str,
    difficulty: str,
    task: str,
    starter_code: str,
    solution_code: str,
    expected_output: str,
    tags: list[str],
    question_type: str = "code_completion",
    xp_reward: int | None = None,
    time_estimate_mins: int | None = None,
) -> dict:
    xp = xp_reward or {"basic": 8, "intermediate": 18, "advanced": 30}[difficulty]
    mins = time_estimate_mins or {"basic": 4, "intermediate": 8, "advanced": 12}[difficulty]
    return {
        "title": title,
        "slug": slug,
        "difficulty": difficulty,
        "question_type": question_type,
        "problem_statement": (
            f"## {title}\n\n"
            f"{task}\n\n"
            f"**Expected output:**\n```\n{expected_output}\n```\n"
        ),
        "starter_code": starter_code,
        "expected_output": expected_output,
        "tags": tags,
        "xp_reward": xp,
        "time_estimate_mins": mins,
        "solutions": [
            {
                "title": "Solution",
                "code": solution_code,
                "explanation": "",
                "is_optimal": True,
            }
        ],
    }


def _functional_questions() -> list[dict]:
    questions: list[dict] = []
    questions.extend(
        [
            _q(
                title="Map Squares",
                slug="py-fn-map-squares",
                difficulty="basic",
                task="Use `map()` to square `[1, 2, 3, 4]`, convert to a list, and print it.",
                starter_code="nums = [1, 2, 3, 4]\n# use map to square and print\n",
                solution_code="nums = [1, 2, 3, 4]\nprint(list(map(lambda x: x * x, nums)))",
                expected_output="[1, 4, 9, 16]",
                tags=["functional", "map", "lambda"],
            ),
            _q(
                title="Filter Even Numbers",
                slug="py-fn-filter-evens",
                difficulty="basic",
                task="Use `filter()` to keep only even numbers from `range(1, 8)` and print the list.",
                starter_code="nums = list(range(1, 8))\n# filter evens and print\n",
                solution_code="nums = list(range(1, 8))\nprint(list(filter(lambda x: x % 2 == 0, nums)))",
                expected_output="[2, 4, 6]",
                tags=["functional", "filter"],
            ),
            _q(
                title="Sort by String Length",
                slug="py-fn-sorted-key-len",
                difficulty="basic",
                task="Sort `['pear', 'kiwi', 'banana']` by length using `sorted(..., key=...)` and print.",
                starter_code="words = ['pear', 'kiwi', 'banana']\n# sort by length and print\n",
                solution_code="words = ['pear', 'kiwi', 'banana']\nprint(sorted(words, key=len))",
                expected_output="['pear', 'kiwi', 'banana']",
                tags=["functional", "sorted", "key"],
            ),
            _q(
                title="Any Predicate Match",
                slug="py-fn-any-positive",
                difficulty="basic",
                task="Given `[-2, -1, 0, 5]`, print whether any value is greater than 0 using `any()`.",
                starter_code="nums = [-2, -1, 0, 5]\n# print any positive\n",
                solution_code="nums = [-2, -1, 0, 5]\nprint(any(x > 0 for x in nums))",
                expected_output="True",
                tags=["functional", "any"],
            ),
            _q(
                title="All Lowercase Check",
                slug="py-fn-all-lowercase",
                difficulty="basic",
                task="Check with `all()` that every word in `['red', 'blue', 'green']` is lowercase.",
                starter_code="words = ['red', 'blue', 'green']\n# print all lowercase\n",
                solution_code="words = ['red', 'blue', 'green']\nprint(all(w.islower() for w in words))",
                expected_output="True",
                tags=["functional", "all"],
            ),
            _q(
                title="Zip and Sum Pairs",
                slug="py-fn-zip-sum",
                difficulty="basic",
                task="Use `zip()` on `[1,2,3]` and `[4,5,6]`, sum pairwise, and print the result list.",
                starter_code="a = [1, 2, 3]\nb = [4, 5, 6]\n# zip and sum\n",
                solution_code="a = [1, 2, 3]\nb = [4, 5, 6]\nprint([x + y for x, y in zip(a, b)])",
                expected_output="[5, 7, 9]",
                tags=["functional", "zip"],
            ),
            _q(
                title="Enumerate to Index Map",
                slug="py-fn-enumerate-map",
                difficulty="basic",
                task="Create `{index: value}` for `['a', 'b', 'c']` using `enumerate()` and print it.",
                starter_code="letters = ['a', 'b', 'c']\n# build index->value dict\n",
                solution_code="letters = ['a', 'b', 'c']\nprint({i: v for i, v in enumerate(letters)})",
                expected_output="{0: 'a', 1: 'b', 2: 'c'}",
                tags=["functional", "enumerate", "dict"],
            ),
            _q(
                title="Generator in Sum",
                slug="py-fn-sum-generator",
                difficulty="basic",
                task="Use a generator expression inside `sum()` to add odd numbers from 1 to 9.",
                starter_code="# sum odd numbers from 1..9 using generator expression\n",
                solution_code="print(sum(n for n in range(1, 10) if n % 2 == 1))",
                expected_output="25",
                tags=["functional", "generator"],
            ),
            _q(
                title="Reduce Product",
                slug="py-fn-reduce-product",
                difficulty="intermediate",
                task="Use `functools.reduce()` to compute the product of `[2, 3, 4]`.",
                starter_code="from functools import reduce\nnums = [2, 3, 4]\n# reduce to product\n",
                solution_code="from functools import reduce\nnums = [2, 3, 4]\nprint(reduce(lambda a, b: a * b, nums))",
                expected_output="24",
                tags=["functional", "reduce"],
            ),
            _q(
                title="Partial Function Power",
                slug="py-fn-partial-power",
                difficulty="intermediate",
                task="Use `functools.partial` with `pow` to create `square`, then print `square(9)`.",
                starter_code="from functools import partial\n# create square via partial(pow, exp=2)\n",
                solution_code="from functools import partial\nsquare = partial(pow, exp=2)\nprint(square(9))",
                expected_output="81",
                tags=["functional", "partial"],
            ),
            _q(
                title="Operator Itemgetter Sort",
                slug="py-fn-itemgetter-sort",
                difficulty="intermediate",
                task="Sort `[('sam', 3), ('alex', 1), ('mia', 2)]` by the second item using `operator.itemgetter`.",
                starter_code="from operator import itemgetter\nrows = [('sam', 3), ('alex', 1), ('mia', 2)]\n# sort by index 1\n",
                solution_code="from operator import itemgetter\nrows = [('sam', 3), ('alex', 1), ('mia', 2)]\nprint(sorted(rows, key=itemgetter(1)))",
                expected_output="[('alex', 1), ('mia', 2), ('sam', 3)]",
                tags=["functional", "operator", "sorting"],
            ),
            _q(
                title="Simple Function Composition",
                slug="py-fn-compose-two",
                difficulty="intermediate",
                task="Compose `double` and `inc` so the final call computes `double(inc(5))`.",
                starter_code="def inc(x):\n    return x + 1\n\ndef double(x):\n    return x * 2\n\n# compose and print result for 5\n",
                solution_code="def inc(x):\n    return x + 1\n\ndef double(x):\n    return x * 2\n\ncompose = lambda f, g: lambda x: f(g(x))\nprint(compose(double, inc)(5))",
                expected_output="12",
                tags=["functional", "composition"],
            ),
            _q(
                title="Accumulate Running Totals",
                slug="py-fn-accumulate-last",
                difficulty="intermediate",
                task="Use `itertools.accumulate` on `[3, 1, 4]` and print the final accumulated value.",
                starter_code="from itertools import accumulate\nnums = [3, 1, 4]\n# print last running total\n",
                solution_code="from itertools import accumulate\nnums = [3, 1, 4]\nprint(list(accumulate(nums))[-1])",
                expected_output="8",
                tags=["functional", "itertools"],
            ),
            _q(
                title="Starmap Multiply",
                slug="py-fn-starmap-mul",
                difficulty="intermediate",
                task="Use `itertools.starmap` and `operator.mul` on `[(2,5), (3,4)]`, print list.",
                starter_code="from itertools import starmap\nfrom operator import mul\npairs = [(2, 5), (3, 4)]\n# starmap multiply\n",
                solution_code="from itertools import starmap\nfrom operator import mul\npairs = [(2, 5), (3, 4)]\nprint(list(starmap(mul, pairs)))",
                expected_output="[10, 12]",
                tags=["functional", "starmap"],
            ),
            _q(
                title="Groupby First Letter",
                slug="py-fn-groupby-first-letter",
                difficulty="intermediate",
                task="Sort `['apple','ant','ball']`, group with `itertools.groupby` by first letter, and print key counts as dict.",
                starter_code="from itertools import groupby\nwords = ['apple', 'ant', 'ball']\n# sort, groupby first letter, print counts dict\n",
                solution_code="from itertools import groupby\nwords = sorted(['apple', 'ant', 'ball'])\nprint({k: len(list(g)) for k, g in groupby(words, key=lambda w: w[0])})",
                expected_output="{'a': 2, 'b': 1}",
                tags=["functional", "groupby"],
            ),
            _q(
                title="Map then Filter Pipeline",
                slug="py-fn-map-filter-pipeline",
                difficulty="intermediate",
                task="Square numbers 1..6 with `map`, then filter values over 15 and print the list.",
                starter_code="# map square then filter > 15\n",
                solution_code="squared = map(lambda x: x * x, range(1, 7))\nprint(list(filter(lambda x: x > 15, squared)))",
                expected_output="[16, 25, 36]",
                tags=["functional", "pipeline"],
            ),
            _q(
                title="Variadic Compose",
                slug="py-fn-variadic-compose",
                difficulty="advanced",
                task="Implement `compose(*funcs)` and apply it to `add1`, `times2`, `minus3` on input 10.",
                starter_code="from functools import reduce\n\ndef add1(x):\n    return x + 1\n\ndef times2(x):\n    return x * 2\n\ndef minus3(x):\n    return x - 3\n\n# implement compose(*funcs), then print compose(minus3, times2, add1)(10)\n",
                solution_code="from functools import reduce\n\ndef add1(x):\n    return x + 1\n\ndef times2(x):\n    return x * 2\n\ndef minus3(x):\n    return x - 3\n\ndef compose(*funcs):\n    return reduce(lambda f, g: lambda x: f(g(x)), funcs)\n\nprint(compose(minus3, times2, add1)(10))",
                expected_output="19",
                tags=["functional", "composition", "advanced"],
            ),
            _q(
                title="Immutable Dataclass Update",
                slug="py-fn-immutability-replace",
                difficulty="advanced",
                task="Use `dataclasses.replace` to update a frozen dataclass value and print old/new points.",
                starter_code="from dataclasses import dataclass, replace\n\n@dataclass(frozen=True)\nclass Point:\n    x: int\n    y: int\n\np1 = Point(2, 3)\n# create p2 with x=10 and print p1 then p2\n",
                solution_code="from dataclasses import dataclass, replace\n\n@dataclass(frozen=True)\nclass Point:\n    x: int\n    y: int\n\np1 = Point(2, 3)\np2 = replace(p1, x=10)\nprint(p1)\nprint(p2)",
                expected_output="Point(x=2, y=3)\nPoint(x=10, y=3)",
                tags=["functional", "immutability", "dataclasses"],
            ),
            _q(
                title="Memoization Decorator",
                slug="py-fn-memoize-fib",
                difficulty="advanced",
                task="Implement a memoized recursive Fibonacci and print `fib(10)`.",
                starter_code="def memoize(fn):\n    # implement cache decorator\n    pass\n\n@memoize\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\nprint(fib(10))\n",
                solution_code="def memoize(fn):\n    cache = {}\n\n    def wrapper(n):\n        if n not in cache:\n            cache[n] = fn(n)\n        return cache[n]\n\n    return wrapper\n\n@memoize\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\nprint(fib(10))",
                expected_output="55",
                tags=["functional", "memoization", "decorators"],
            ),
            _q(
                title="Closure-based Curry",
                slug="py-fn-curry-closure",
                difficulty="advanced",
                task="Write `curry_add(a)` that returns a function adding `a` to `b`, then print `curry_add(7)(5)`.",
                starter_code="# define curry_add and print curry_add(7)(5)\n",
                solution_code="def curry_add(a):\n    def inner(b):\n        return a + b\n\n    return inner\n\nprint(curry_add(7)(5))",
                expected_output="12",
                tags=["functional", "closures", "currying"],
            ),
            _q(
                title="Reduce Function Chain",
                slug="py-fn-reduce-function-chain",
                difficulty="advanced",
                task="Apply `[lambda x: x+2, lambda x: x*3, lambda x: x-1]` sequentially to 4 with `reduce` and print.",
                starter_code="from functools import reduce\nfuncs = [lambda x: x + 2, lambda x: x * 3, lambda x: x - 1]\n# reduce over funcs starting at 4\n",
                solution_code="from functools import reduce\nfuncs = [lambda x: x + 2, lambda x: x * 3, lambda x: x - 1]\nprint(reduce(lambda acc, fn: fn(acc), funcs, 4))",
                expected_output="17",
                tags=["functional", "reduce", "pipeline"],
            ),
            _q(
                title="Pure Transform Pipeline",
                slug="py-fn-pure-transform-pipeline",
                difficulty="advanced",
                task="Build a pure pipeline that strips, lowercases, and deduplicates `['  A', 'a ', 'B']` preserving order.",
                starter_code="records = ['  A', 'a ', 'B']\n# normalize and deduplicate preserving first occurrence\n",
                solution_code="records = ['  A', 'a ', 'B']\nnormalized = list(map(lambda s: s.strip().lower(), records))\nout = list(dict.fromkeys(normalized))\nprint(out)",
                expected_output="['a', 'b']",
                tags=["functional", "pure-functions", "advanced"],
            ),
        ]
    )
    return questions


def _comprehension_questions() -> list[dict]:
    return [
        _q(
            title="Squares List Comprehension",
            slug="py-comp-squares",
            difficulty="basic",
            task="Create a list of squares for numbers 1 to 5 using a list comprehension.",
            starter_code="# print squares 1..5 with a list comprehension\n",
            solution_code="print([n * n for n in range(1, 6)])",
            expected_output="[1, 4, 9, 16, 25]",
            tags=["comprehensions", "list"],
        ),
        _q(
            title="Even Numbers List",
            slug="py-comp-evens",
            difficulty="basic",
            task="Use a list comprehension to collect even numbers from 1 to 10.",
            starter_code="# print even numbers 1..10\n",
            solution_code="print([n for n in range(1, 11) if n % 2 == 0])",
            expected_output="[2, 4, 6, 8, 10]",
            tags=["comprehensions", "list"],
        ),
        _q(
            title="Uppercase Words",
            slug="py-comp-uppercase",
            difficulty="basic",
            task="Convert `['py', 'thon']` to uppercase words using comprehension and print.",
            starter_code="words = ['py', 'thon']\n# uppercase with comprehension\n",
            solution_code="words = ['py', 'thon']\nprint([w.upper() for w in words])",
            expected_output="['PY', 'THON']",
            tags=["comprehensions", "strings"],
        ),
        _q(
            title="Flatten Nested List",
            slug="py-comp-flatten",
            difficulty="basic",
            task="Flatten `[[1, 2], [3], [4, 5]]` using a nested list comprehension.",
            starter_code="grid = [[1, 2], [3], [4, 5]]\n# flatten grid\n",
            solution_code="grid = [[1, 2], [3], [4, 5]]\nprint([x for row in grid for x in row])",
            expected_output="[1, 2, 3, 4, 5]",
            tags=["comprehensions", "nested"],
        ),
        _q(
            title="Conditional Labels",
            slug="py-comp-conditional-labels",
            difficulty="basic",
            task="Build labels `['odd', 'even', ...]` for numbers 1..4 via comprehension.",
            starter_code="# build odd/even labels for 1..4\n",
            solution_code="print(['even' if n % 2 == 0 else 'odd' for n in range(1, 5)])",
            expected_output="['odd', 'even', 'odd', 'even']",
            tags=["comprehensions", "conditional"],
        ),
        _q(
            title="Strip and Lower",
            slug="py-comp-strip-lower",
            difficulty="basic",
            task="Normalize `['  A', 'b ', ' C ']` by stripping and lowering each string.",
            starter_code="items = ['  A', 'b ', ' C ']\n# normalize with comprehension\n",
            solution_code="items = ['  A', 'b ', ' C ']\nprint([s.strip().lower() for s in items])",
            expected_output="['a', 'b', 'c']",
            tags=["comprehensions", "strings"],
        ),
        _q(
            title="Length of Words",
            slug="py-comp-word-lengths",
            difficulty="basic",
            task="Create a list with the lengths of `['cat', 'mouse']` using comprehension.",
            starter_code="words = ['cat', 'mouse']\n# print lengths list\n",
            solution_code="words = ['cat', 'mouse']\nprint([len(w) for w in words])",
            expected_output="[3, 5]",
            tags=["comprehensions", "list"],
        ),
        _q(
            title="Vowel Filter",
            slug="py-comp-vowel-filter",
            difficulty="basic",
            task="Extract vowels from `'pythonic'` using a list comprehension.",
            starter_code="s = 'pythonic'\n# collect vowels\n",
            solution_code="s = 'pythonic'\nprint([ch for ch in s if ch in 'aeiou'])",
            expected_output="['o', 'i']",
            tags=["comprehensions", "strings"],
        ),
        _q(
            title="Powers of Two",
            slug="py-comp-powers-two",
            difficulty="basic",
            task="Create `[2**n for n in range(6)]` and print it.",
            starter_code="# print powers of two from exponent 0..5\n",
            solution_code="print([2 ** n for n in range(6)])",
            expected_output="[1, 2, 4, 8, 16, 32]",
            tags=["comprehensions", "math"],
        ),
        _q(
            title="Coordinate Pairs",
            slug="py-comp-coordinate-pairs",
            difficulty="basic",
            task="Generate all `(x, y)` for `x in [1,2]` and `y in [3,4]` using comprehension.",
            starter_code="# print coordinate pairs\n",
            solution_code="print([(x, y) for x in [1, 2] for y in [3, 4]])",
            expected_output="[(1, 3), (1, 4), (2, 3), (2, 4)]",
            tags=["comprehensions", "nested"],
        ),
        _q(
            title="Dict Comprehension Squares",
            slug="py-comp-dict-squares",
            difficulty="intermediate",
            task="Create `{n: n*n}` for 1..4 with dict comprehension and print it.",
            starter_code="# dict comprehension of squares 1..4\n",
            solution_code="print({n: n * n for n in range(1, 5)})",
            expected_output="{1: 1, 2: 4, 3: 9, 4: 16}",
            tags=["comprehensions", "dict"],
        ),
        _q(
            title="Set Comprehension Unique Lower",
            slug="py-comp-set-lower",
            difficulty="intermediate",
            task="Build a lowercase set from `['A', 'a', 'B']` with set comprehension and print sorted list.",
            starter_code="items = ['A', 'a', 'B']\n# lowercase unique set then print sorted list\n",
            solution_code="items = ['A', 'a', 'B']\nprint(sorted({x.lower() for x in items}))",
            expected_output="['a', 'b']",
            tags=["comprehensions", "set"],
        ),
        _q(
            title="Transpose Matrix",
            slug="py-comp-matrix-transpose",
            difficulty="intermediate",
            task="Transpose `[[1,2,3],[4,5,6]]` using nested comprehension.",
            starter_code="m = [[1, 2, 3], [4, 5, 6]]\n# transpose matrix\n",
            solution_code="m = [[1, 2, 3], [4, 5, 6]]\nprint([[row[i] for row in m] for i in range(len(m[0]))])",
            expected_output="[[1, 4], [2, 5], [3, 6]]",
            tags=["comprehensions", "matrix", "nested"],
        ),
        _q(
            title="Nested Filtered Flatten",
            slug="py-comp-filtered-flatten",
            difficulty="intermediate",
            task="Flatten `[[1,2,3],[4,5]]` but keep only odd numbers.",
            starter_code="grid = [[1, 2, 3], [4, 5]]\n# flatten and filter odds\n",
            solution_code="grid = [[1, 2, 3], [4, 5]]\nprint([x for row in grid for x in row if x % 2 == 1])",
            expected_output="[1, 3, 5]",
            tags=["comprehensions", "nested", "filter"],
        ),
        _q(
            title="Map Index to Value",
            slug="py-comp-enumerate-dict",
            difficulty="intermediate",
            task="Build `{index: value}` from `['x','y','z']` with comprehension over `enumerate`.",
            starter_code="letters = ['x', 'y', 'z']\n# build index map\n",
            solution_code="letters = ['x', 'y', 'z']\nprint({i: ch for i, ch in enumerate(letters)})",
            expected_output="{0: 'x', 1: 'y', 2: 'z'}",
            tags=["comprehensions", "enumerate", "dict"],
        ),
        _q(
            title="Comprehension with Zip",
            slug="py-comp-zip-dict",
            difficulty="intermediate",
            task="Use dict comprehension with `zip(['a','b'], [1,2])`.",
            starter_code="# create dict from zipped lists using comprehension\n",
            solution_code="print({k: v for k, v in zip(['a', 'b'], [1, 2])})",
            expected_output="{'a': 1, 'b': 2}",
            tags=["comprehensions", "zip", "dict"],
        ),
        _q(
            title="Word Frequency Map",
            slug="py-comp-word-frequency",
            difficulty="intermediate",
            task="Create a frequency dict for `['a','b','a']` using dict comprehension + count.",
            starter_code="words = ['a', 'b', 'a']\n# build frequency dict\n",
            solution_code="words = ['a', 'b', 'a']\nprint({w: words.count(w) for w in set(words)})",
            expected_output="{'a': 2, 'b': 1}",
            tags=["comprehensions", "dict", "frequency"],
        ),
        _q(
            title="Nested Dict Comprehension",
            slug="py-comp-nested-dict",
            difficulty="intermediate",
            task="Create `{x: {y: x*y for y in [1,2]} for x in [3,4]}` and print.",
            starter_code="# print nested dict comprehension\n",
            solution_code="print({x: {y: x * y for y in [1, 2]} for x in [3, 4]})",
            expected_output="{3: {1: 3, 2: 6}, 4: {1: 4, 2: 8}}",
            tags=["comprehensions", "nested", "dict"],
        ),
        _q(
            title="Generator Expression Sum",
            slug="py-comp-generator-sum",
            difficulty="advanced",
            task="Use a generator expression to sum cubes from 1..4 and print the result.",
            starter_code="# sum cubes 1..4 with generator expression\n",
            solution_code="print(sum(n ** 3 for n in range(1, 5)))",
            expected_output="100",
            tags=["comprehensions", "generator"],
        ),
        _q(
            title="Walrus in Comprehension",
            slug="py-comp-walrus-length-filter",
            difficulty="advanced",
            task="Use walrus in a list comprehension to keep words longer than 3 chars and store lengths.",
            starter_code="words = ['ai', 'model', 'code', 'py']\n# use walrus to collect lengths > 3\n",
            solution_code="words = ['ai', 'model', 'code', 'py']\nprint([l for w in words if (l := len(w)) > 3])",
            expected_output="[5, 4]",
            tags=["comprehensions", "walrus", "advanced"],
            time_estimate_mins=10,
        ),
        _q(
            title="Cartesian Product with Condition",
            slug="py-comp-cartesian-condition",
            difficulty="advanced",
            task="Build pairs `(x, y)` for `x,y in range(4)` where `x < y` using comprehension.",
            starter_code="# print all pairs (x,y) with x<y for range(4)\n",
            solution_code="print([(x, y) for x in range(4) for y in range(4) if x < y])",
            expected_output="[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]",
            tags=["comprehensions", "advanced", "nested"],
        ),
        _q(
            title="Lookup Dict from Tuples",
            slug="py-comp-tuple-lookup",
            difficulty="advanced",
            task="From `[('u1', 'Ana'), ('u2', 'Raj')]`, build `{id_: name}` using comprehension.",
            starter_code="rows = [('u1', 'Ana'), ('u2', 'Raj')]\n# build lookup dict\n",
            solution_code="rows = [('u1', 'Ana'), ('u2', 'Raj')]\nprint({id_: name for id_, name in rows})",
            expected_output="{'u1': 'Ana', 'u2': 'Raj'}",
            tags=["comprehensions", "dict", "advanced"],
        ),
        _q(
            title="Nested Conditional Dict",
            slug="py-comp-nested-conditional-dict",
            difficulty="advanced",
            task="Create `{n: ('even' if n%2==0 else 'odd') for n in range(1,6)}` and print.",
            starter_code="# build parity dict for 1..5\n",
            solution_code="print({n: ('even' if n % 2 == 0 else 'odd') for n in range(1, 6)})",
            expected_output="{1: 'odd', 2: 'even', 3: 'odd', 4: 'even', 5: 'odd'}",
            tags=["comprehensions", "conditional", "advanced"],
        ),
        _q(
            title="Compressed Unique Flatten",
            slug="py-comp-unique-flatten-advanced",
            difficulty="advanced",
            task="Flatten `[[1,2],[2,3],[3,4]]` and keep unique values in first-seen order.",
            starter_code="grid = [[1, 2], [2, 3], [3, 4]]\n# flatten + unique preserving order\n",
            solution_code="grid = [[1, 2], [2, 3], [3, 4]]\nflat = [x for row in grid for x in row]\nprint(list(dict.fromkeys(flat)))",
            expected_output="[1, 2, 3, 4]",
            tags=["comprehensions", "advanced", "data-cleaning"],
        ),
    ]


def _type_hint_questions() -> list[dict]:
    return [
        _q(
            title="Function Parameter Annotation",
            slug="py-type-param-annotation",
            difficulty="basic",
            task="Define `def add(a: int, b: int) -> int` and print `add(2, 5)`.",
            starter_code="# define annotated add() and print add(2, 5)\n",
            solution_code="def add(a: int, b: int) -> int:\n    return a + b\n\nprint(add(2, 5))",
            expected_output="7",
            tags=["type-hints", "annotations"],
        ),
        _q(
            title="Variable Annotation",
            slug="py-type-variable-annotation",
            difficulty="basic",
            task="Create `name: str = 'python'` and print it uppercased.",
            starter_code="# add a variable annotation and print upper-case value\n",
            solution_code="name: str = 'python'\nprint(name.upper())",
            expected_output="PYTHON",
            tags=["type-hints", "variables"],
        ),
        _q(
            title="List Annotation",
            slug="py-type-list-annotation",
            difficulty="basic",
            task="Annotate `nums` as `list[int]`, sum it, and print result for `[3, 4, 5]`.",
            starter_code="# annotate nums as list[int], print sum\n",
            solution_code="nums: list[int] = [3, 4, 5]\nprint(sum(nums))",
            expected_output="12",
            tags=["type-hints", "list"],
        ),
        _q(
            title="Dict Annotation",
            slug="py-type-dict-annotation",
            difficulty="basic",
            task="Annotate a score dict `dict[str, int]` and print value for key `'math'`.",
            starter_code="# annotate dict and print math score\n",
            solution_code="scores: dict[str, int] = {'math': 92, 'eng': 87}\nprint(scores['math'])",
            expected_output="92",
            tags=["type-hints", "dict"],
        ),
        _q(
            title="Return Type Annotation",
            slug="py-type-return-annotation",
            difficulty="basic",
            task="Annotate a function returning `str` and print greeting for `'Ada'`.",
            starter_code="# define greet(name: str) -> str and print\n",
            solution_code="def greet(name: str) -> str:\n    return f'Hi {name}'\n\nprint(greet('Ada'))",
            expected_output="Hi Ada",
            tags=["type-hints", "functions"],
        ),
        _q(
            title="Optional Annotation",
            slug="py-type-optional-basic",
            difficulty="basic",
            task="Use `Optional[str]` for a nickname and print `'guest'` when it is `None`.",
            starter_code="from typing import Optional\nnick: Optional[str] = None\n# print nick or guest\n",
            solution_code="from typing import Optional\nnick: Optional[str] = None\nprint(nick or 'guest')",
            expected_output="guest",
            tags=["type-hints", "optional"],
        ),
        _q(
            title="Tuple Annotation",
            slug="py-type-tuple-annotation",
            difficulty="basic",
            task="Annotate `point` as `tuple[int, int]` and print sum of coordinates.",
            starter_code="# annotate tuple[int, int] and print sum\n",
            solution_code="point: tuple[int, int] = (4, 6)\nprint(point[0] + point[1])",
            expected_output="10",
            tags=["type-hints", "tuple"],
        ),
        _q(
            title="Reading __annotations__",
            slug="py-type-read-annotations",
            difficulty="basic",
            task="Define `def scale(x: float, k: float) -> float` and print whether `'x'` exists in `__annotations__`.",
            starter_code="# define function with annotations and inspect __annotations__\n",
            solution_code="def scale(x: float, k: float) -> float:\n    return x * k\n\nprint('x' in scale.__annotations__)",
            expected_output="True",
            tags=["type-hints", "introspection"],
        ),
        _q(
            title="Union Return",
            slug="py-type-union-return",
            difficulty="intermediate",
            task="Use `Union[int, str]` in a parser: return int for digit strings, else `'bad'`. Print parser('42').",
            starter_code="from typing import Union\n# define parser and print parser('42')\n",
            solution_code="from typing import Union\n\ndef parser(raw: str) -> Union[int, str]:\n    return int(raw) if raw.isdigit() else 'bad'\n\nprint(parser('42'))",
            expected_output="42",
            tags=["type-hints", "union"],
        ),
        _q(
            title="Optional Argument Processing",
            slug="py-type-optional-arg",
            difficulty="intermediate",
            task="Write `normalize(text: Optional[str]) -> str` returning stripped lowercase or empty string.",
            starter_code="from typing import Optional\n# implement normalize and print normalize('  HeLLo ')\n",
            solution_code="from typing import Optional\n\ndef normalize(text: Optional[str]) -> str:\n    return text.strip().lower() if text else ''\n\nprint(normalize('  HeLLo '))",
            expected_output="hello",
            tags=["type-hints", "optional"],
        ),
        _q(
            title="TypeAlias for UserId",
            slug="py-type-alias-userid",
            difficulty="intermediate",
            task="Create a `TypeAlias` named `UserId = int`, annotate a value, and print value + 1.",
            starter_code="from typing import TypeAlias\n# define UserId alias and print uid + 1\n",
            solution_code="from typing import TypeAlias\n\nUserId: TypeAlias = int\nuid: UserId = 100\nprint(uid + 1)",
            expected_output="101",
            tags=["type-hints", "type-alias"],
        ),
        _q(
            title="TypeVar Identity",
            slug="py-type-typevar-identity",
            difficulty="intermediate",
            task="Use `TypeVar` in `identity(x: T) -> T` and print `identity('ok')`.",
            starter_code="from typing import TypeVar\nT = TypeVar('T')\n# define identity and print identity('ok')\n",
            solution_code="from typing import TypeVar\nT = TypeVar('T')\n\ndef identity(x: T) -> T:\n    return x\n\nprint(identity('ok'))",
            expected_output="ok",
            tags=["type-hints", "typevar", "generic"],
        ),
        _q(
            title="Generic Stack Class",
            slug="py-type-generic-stack",
            difficulty="intermediate",
            task="Create a generic `Stack[T]` with `push` and `pop`, push 3 values, then print popped value.",
            starter_code="from typing import Generic, TypeVar\nT = TypeVar('T')\n# implement Stack and print last popped item\n",
            solution_code="from typing import Generic, TypeVar\nT = TypeVar('T')\n\nclass Stack(Generic[T]):\n    def __init__(self) -> None:\n        self.items: list[T] = []\n\n    def push(self, x: T) -> None:\n        self.items.append(x)\n\n    def pop(self) -> T:\n        return self.items.pop()\n\ns = Stack[int]()\ns.push(1)\ns.push(2)\ns.push(3)\nprint(s.pop())",
            expected_output="3",
            tags=["type-hints", "generic", "class"],
            time_estimate_mins=10,
        ),
        _q(
            title="Typed List Filter",
            slug="py-type-list-filter",
            difficulty="intermediate",
            task="Annotate and filter `list[int]` for values > 5 from `[2,8,4,9]` and print.",
            starter_code="# annotate list and filter > 5\n",
            solution_code="nums: list[int] = [2, 8, 4, 9]\nprint([n for n in nums if n > 5])",
            expected_output="[8, 9]",
            tags=["type-hints", "list"],
        ),
        _q(
            title="get_type_hints Utility",
            slug="py-type-get-type-hints",
            difficulty="intermediate",
            task="Use `typing.get_type_hints` on a function and print whether `'return'` key exists.",
            starter_code="from typing import get_type_hints\n# define function with annotations, inspect hints\n",
            solution_code="from typing import get_type_hints\n\ndef area(r: float) -> float:\n    return 3.14 * r * r\n\nprint('return' in get_type_hints(area))",
            expected_output="True",
            tags=["type-hints", "introspection"],
        ),
        _q(
            title="Callable Annotation",
            slug="py-type-callable-annotation",
            difficulty="intermediate",
            task="Annotate `apply_twice(fn, x)` with `Callable[[int], int]` and print applying `lambda n: n+2` to 5.",
            starter_code="from typing import Callable\n# define apply_twice and print result\n",
            solution_code="from typing import Callable\n\ndef apply_twice(fn: Callable[[int], int], x: int) -> int:\n    return fn(fn(x))\n\nprint(apply_twice(lambda n: n + 2, 5))",
            expected_output="9",
            tags=["type-hints", "callable"],
        ),
        _q(
            title="Literal Options",
            slug="py-type-literal-options",
            difficulty="intermediate",
            task="Use `Literal['r', 'w']` in a function and print `'w'` mode returned unchanged.",
            starter_code="from typing import Literal\n# define choose_mode and print choose_mode('w')\n",
            solution_code="from typing import Literal\n\ndef choose_mode(mode: Literal['r', 'w']) -> str:\n    return mode\n\nprint(choose_mode('w'))",
            expected_output="w",
            tags=["type-hints", "literal"],
        ),
        _q(
            title="TypedDict Basics",
            slug="py-type-typeddict-basic",
            difficulty="intermediate",
            task="Define a `TypedDict` `User` with `name` and `age`, create one, and print age.",
            starter_code="from typing import TypedDict\n# define User TypedDict and print age\n",
            solution_code="from typing import TypedDict\n\nclass User(TypedDict):\n    name: str\n    age: int\n\nu: User = {'name': 'Ivy', 'age': 31}\nprint(u['age'])",
            expected_output="31",
            tags=["type-hints", "typeddict"],
        ),
        _q(
            title="Protocol Structural Typing",
            slug="py-type-protocol-supports-len",
            difficulty="advanced",
            task="Create a `Protocol` with `__len__`, write a function using it, and print length of `'abcde'`.",
            starter_code="from typing import Protocol\n# define protocol and function, then print result\n",
            solution_code="from typing import Protocol\n\nclass SupportsLen(Protocol):\n    def __len__(self) -> int: ...\n\ndef size(x: SupportsLen) -> int:\n    return len(x)\n\nprint(size('abcde'))",
            expected_output="5",
            tags=["type-hints", "protocol", "advanced"],
        ),
        _q(
            title="Overload Signatures",
            slug="py-type-overload-signatures",
            difficulty="advanced",
            task="Use `@overload` for `to_text` handling int/str, implement runtime body, and print `to_text(7)`.",
            starter_code="from typing import overload\n# add overloads and implementation\n",
            solution_code="from typing import overload\n\n@overload\ndef to_text(x: int) -> str: ...\n\n@overload\ndef to_text(x: str) -> str: ...\n\ndef to_text(x: int | str) -> str:\n    return str(x)\n\nprint(to_text(7))",
            expected_output="7",
            tags=["type-hints", "overload", "advanced"],
            time_estimate_mins=14,
        ),
        _q(
            title="TypedDict Optional Keys",
            slug="py-type-typeddict-notrequired",
            difficulty="advanced",
            task="Use `NotRequired` in a `TypedDict` and print whether optional key is absent.",
            starter_code="from typing import NotRequired, TypedDict\n# define Movie TypedDict and print key absence\n",
            solution_code="from typing import NotRequired, TypedDict\n\nclass Movie(TypedDict):\n    title: str\n    year: NotRequired[int]\n\nm: Movie = {'title': 'Arrival'}\nprint('year' not in m)",
            expected_output="True",
            tags=["type-hints", "typeddict", "advanced"],
        ),
        _q(
            title="NewType UserId",
            slug="py-type-newtype-userid",
            difficulty="advanced",
            task="Create `UserId = NewType('UserId', int)`, instantiate it, and print `int(uid) + 2`.",
            starter_code="from typing import NewType\n# create NewType and print int value + 2\n",
            solution_code="from typing import NewType\n\nUserId = NewType('UserId', int)\nuid = UserId(40)\nprint(int(uid) + 2)",
            expected_output="42",
            tags=["type-hints", "newtype", "advanced"],
        ),
        _q(
            title="Runtime Type Guard",
            slug="py-type-typeguard-runtime",
            difficulty="advanced",
            task="Implement `is_int_list` returning `TypeGuard[list[int]]` and print result for `[1,2,3]`.",
            starter_code="from typing import Any, TypeGuard\n# implement is_int_list and print check\n",
            solution_code="from typing import Any, TypeGuard\n\ndef is_int_list(v: list[Any]) -> TypeGuard[list[int]]:\n    return all(isinstance(x, int) for x in v)\n\nprint(is_int_list([1, 2, 3]))",
            expected_output="True",
            tags=["type-hints", "typeguard", "advanced"],
            time_estimate_mins=14,
        ),
        _q(
            title="Annotated Metadata",
            slug="py-type-annotated-metadata",
            difficulty="advanced",
            task="Use `Annotated[int, 'positive']` in a function signature and print return for 5.",
            starter_code="from typing import Annotated\n# define function using Annotated and print\n",
            solution_code="from typing import Annotated\n\ndef identity(x: Annotated[int, 'positive']) -> int:\n    return x\n\nprint(identity(5))",
            expected_output="5",
            tags=["type-hints", "annotated", "advanced"],
        ),
        _q(
            title="Generic Dataclass Box",
            slug="py-type-generic-dataclass-box",
            difficulty="advanced",
            task="Create a generic dataclass `Box[T]` and print boxed string value.",
            starter_code="from dataclasses import dataclass\nfrom typing import Generic, TypeVar\nT = TypeVar('T')\n# define Box dataclass and print value\n",
            solution_code="from dataclasses import dataclass\nfrom typing import Generic, TypeVar\nT = TypeVar('T')\n\n@dataclass\nclass Box(Generic[T]):\n    value: T\n\nprint(Box[str]('typed').value)",
            expected_output="typed",
            tags=["type-hints", "generics", "dataclass", "advanced"],
        ),
        _q(
            title="Final Annotation Constant",
            slug="py-type-final-constant",
            difficulty="advanced",
            task="Annotate `MAX_RETRIES` with `Final[int]`, assign 5, and print it.",
            starter_code="from typing import Final\n# define MAX_RETRIES as Final[int] and print\n",
            solution_code="from typing import Final\n\nMAX_RETRIES: Final[int] = 5\nprint(MAX_RETRIES)",
            expected_output="5",
            tags=["type-hints", "final", "advanced"],
        ),
    ]


def _testing_questions() -> list[dict]:
    return [
        _q(
            title="Simple Assert",
            slug="py-test-simple-assert",
            difficulty="basic",
            task="Write a function `add` and assert `add(2, 3) == 5`, then print `'ok'`.",
            starter_code="# define add and assert result\n",
            solution_code="def add(a, b):\n    return a + b\n\nassert add(2, 3) == 5\nprint('ok')",
            expected_output="ok",
            tags=["testing", "assert"],
        ),
        _q(
            title="Boolean Assertion",
            slug="py-test-boolean-assert",
            difficulty="basic",
            task="Assert that `'abc'.islower()` is true, then print `'pass'`.",
            starter_code="# assert lowercase behavior\n",
            solution_code="assert 'abc'.islower()\nprint('pass')",
            expected_output="pass",
            tags=["testing", "assert"],
        ),
        _q(
            title="Exception Assertion with try",
            slug="py-test-exception-try",
            difficulty="basic",
            task="Verify `int('x')` raises `ValueError` using try/except and print `'caught'`.",
            starter_code="# catch ValueError from int('x')\n",
            solution_code="try:\n    int('x')\nexcept ValueError:\n    print('caught')",
            expected_output="caught",
            tags=["testing", "exceptions"],
        ),
        _q(
            title="Arrange-Act-Assert Pattern",
            slug="py-test-aaa-pattern",
            difficulty="basic",
            task="Use AAA comments to test `double(4)` equals 8 and print `'aaa-ok'`.",
            starter_code="# arrange, act, assert for double()\n",
            solution_code="def double(x):\n    return x * 2\n\n# arrange\nvalue = 4\n# act\nout = double(value)\n# assert\nassert out == 8\nprint('aaa-ok')",
            expected_output="aaa-ok",
            tags=["testing", "patterns"],
        ),
        _q(
            title="String Function Test",
            slug="py-test-string-func",
            difficulty="basic",
            task="Test that `strip()` removes spaces from `' hi '` and print `'ok'` if assertion passes.",
            starter_code="# assert strip behavior\n",
            solution_code="assert ' hi '.strip() == 'hi'\nprint('ok')",
            expected_output="ok",
            tags=["testing", "strings"],
        ),
        _q(
            title="List Length Test",
            slug="py-test-list-len",
            difficulty="basic",
            task="Assert length of `[1,2,3,4]` is 4 and print `'len-ok'`.",
            starter_code="# assert list length\n",
            solution_code="assert len([1, 2, 3, 4]) == 4\nprint('len-ok')",
            expected_output="len-ok",
            tags=["testing", "collections"],
        ),
        _q(
            title="Range Membership Test",
            slug="py-test-membership",
            difficulty="basic",
            task="Assert that 5 is in `range(10)` then print `'in-ok'`.",
            starter_code="# membership assert\n",
            solution_code="assert 5 in range(10)\nprint('in-ok')",
            expected_output="in-ok",
            tags=["testing", "assert"],
        ),
        _q(
            title="None Return Test",
            slug="py-test-none-return",
            difficulty="basic",
            task="Define a function returning None and assert result is None.",
            starter_code="# define noop and test None return\n",
            solution_code="def noop():\n    return None\n\nassert noop() is None\nprint('none-ok')",
            expected_output="none-ok",
            tags=["testing", "functions"],
        ),
        _q(
            title="pytest-style Function Name",
            slug="py-test-pytest-style",
            difficulty="intermediate",
            task="Define `test_addition()` containing an assert, call it manually, and print `'pytest-style'`.",
            starter_code="# define and call test_addition\n",
            solution_code="def test_addition():\n    assert 2 + 2 == 4\n\ntest_addition()\nprint('pytest-style')",
            expected_output="pytest-style",
            tags=["testing", "pytest"],
        ),
        _q(
            title="Parametrized Cases with Loop",
            slug="py-test-param-cases-loop",
            difficulty="intermediate",
            task="Loop through test cases `[(2,4), (3,9)]` for square function, assert each, print `'cases-ok'`.",
            starter_code="# test square function with multiple cases\n",
            solution_code="def square(x):\n    return x * x\n\nfor inp, exp in [(2, 4), (3, 9)]:\n    assert square(inp) == exp\nprint('cases-ok')",
            expected_output="cases-ok",
            tags=["testing", "parametrize"],
        ),
        _q(
            title="Fixture-like Setup Helper",
            slug="py-test-fixture-like-helper",
            difficulty="intermediate",
            task="Create a setup helper returning a sample dict, use it in a test assert, then print `'fixture-ok'`.",
            starter_code="# create fixture-like helper and test with it\n",
            solution_code="def sample_user():\n    return {'name': 'Ana', 'active': True}\n\nu = sample_user()\nassert u['active']\nprint('fixture-ok')",
            expected_output="fixture-ok",
            tags=["testing", "fixtures"],
        ),
        _q(
            title="Mock Function with patch",
            slug="py-test-mock-patch",
            difficulty="intermediate",
            task="Use `unittest.mock.patch` to patch `time.time` to 123.0 and print returned value as int.",
            starter_code="from unittest.mock import patch\nimport time\n# patch time.time and print int result\n",
            solution_code="from unittest.mock import patch\nimport time\n\nwith patch('time.time', return_value=123.0):\n    print(int(time.time()))",
            expected_output="123",
            tags=["testing", "mocking"],
        ),
        _q(
            title="Raises Helper Function",
            slug="py-test-raises-helper",
            difficulty="intermediate",
            task="Write helper `assert_raises_value_error(fn)` and use it with a function that calls `int('x')`.",
            starter_code="# implement assert_raises_value_error and print result\n",
            solution_code="def assert_raises_value_error(fn):\n    try:\n        fn()\n    except ValueError:\n        return True\n    return False\n\nprint(assert_raises_value_error(lambda: int('x')))",
            expected_output="True",
            tags=["testing", "exceptions", "helpers"],
        ),
        _q(
            title="State Isolation Check",
            slug="py-test-state-isolation",
            difficulty="intermediate",
            task="Test that two independent list instances do not share state and print `'isolated'`.",
            starter_code="# verify state isolation between list instances\n",
            solution_code="a = []\nb = []\na.append(1)\nassert b == []\nprint('isolated')",
            expected_output="isolated",
            tags=["testing", "isolation"],
        ),
        _q(
            title="Monkeypatch-like Env Test",
            slug="py-test-env-monkeypatch-like",
            difficulty="intermediate",
            task="Temporarily set `os.environ['MODE']='test'`, assert value, then print it.",
            starter_code="import os\n# set env var, assert, print\n",
            solution_code="import os\nos.environ['MODE'] = 'test'\nassert os.getenv('MODE') == 'test'\nprint(os.environ['MODE'])",
            expected_output="test",
            tags=["testing", "environment"],
        ),
        _q(
            title="CSV Parser Test",
            slug="py-test-csv-parser",
            difficulty="intermediate",
            task="Test a tiny parser that splits `'a,b,c'` by comma and assert list length is 3.",
            starter_code="# test parse_csv function\n",
            solution_code="def parse_csv(row: str) -> list[str]:\n    return row.split(',')\n\nassert len(parse_csv('a,b,c')) == 3\nprint('csv-ok')",
            expected_output="csv-ok",
            tags=["testing", "parsing"],
        ),
        _q(
            title="Expected Failure Pattern",
            slug="py-test-expected-failure-pattern",
            difficulty="intermediate",
            task="Show an expected failure pattern by catching `AssertionError` and printing `'xfail-simulated'`.",
            starter_code="# simulate expected failure\n",
            solution_code="try:\n    assert 2 * 2 == 5\nexcept AssertionError:\n    print('xfail-simulated')",
            expected_output="xfail-simulated",
            tags=["testing", "pytest", "xfail"],
        ),
        _q(
            title="Table-driven Assertions",
            slug="py-test-table-driven",
            difficulty="intermediate",
            task="Use a table of `[(1,1,2), (2,3,5)]` to test `add(a,b)` in a loop and print `'table-ok'`.",
            starter_code="# use table-driven tests for add()\n",
            solution_code="def add(a: int, b: int) -> int:\n    return a + b\n\nfor a, b, exp in [(1, 1, 2), (2, 3, 5)]:\n    assert add(a, b) == exp\nprint('table-ok')",
            expected_output="table-ok",
            tags=["testing", "table-driven", "parametrize"],
        ),
        _q(
            title="Refactor to Testable Function",
            slug="py-test-refactor-testable",
            difficulty="advanced",
            task="Refactor logic into pure function `total(nums)` and test deterministic output for `[1,2,3]`.",
            starter_code="# define total and assert\n",
            solution_code="def total(nums: list[int]) -> int:\n    return sum(nums)\n\nassert total([1, 2, 3]) == 6\nprint('pure-ok')",
            expected_output="pure-ok",
            tags=["testing", "design", "advanced"],
        ),
        _q(
            title="Property-like Invariant Test",
            slug="py-test-property-like-invariant",
            difficulty="advanced",
            task="For values 1..20, assert `x + 0 == x` and print `'invariant-ok'`.",
            starter_code="# check identity invariant for addition\n",
            solution_code="for x in range(1, 21):\n    assert x + 0 == x\nprint('invariant-ok')",
            expected_output="invariant-ok",
            tags=["testing", "invariants", "advanced"],
        ),
        _q(
            title="Golden Output Comparison",
            slug="py-test-golden-output",
            difficulty="advanced",
            task="Compare function output against golden string `'HELLO'` and print `'golden-ok'`.",
            starter_code="# compare function output with golden value\n",
            solution_code="def transform(s: str) -> str:\n    return s.upper()\n\ngolden = 'HELLO'\nassert transform('hello') == golden\nprint('golden-ok')",
            expected_output="golden-ok",
            tags=["testing", "golden-files", "advanced"],
        ),
        _q(
            title="Patch Dependency Call Count",
            slug="py-test-patch-call-count",
            difficulty="advanced",
            task="Patch a helper with `Mock`, call it 3 times, and print call count.",
            starter_code="from unittest.mock import Mock\n# call mocked helper 3 times and print count\n",
            solution_code="from unittest.mock import Mock\n\nhelper = Mock(return_value=1)\nfor _ in range(3):\n    helper()\nprint(helper.call_count)",
            expected_output="3",
            tags=["testing", "mocking", "advanced"],
        ),
        _q(
            title="Boundary Value Tests",
            slug="py-test-boundary-values",
            difficulty="advanced",
            task="Test `clamp(x)` for boundary inputs -1, 0, 10, 11 and print `'boundary-ok'`.",
            starter_code="# implement clamp and boundary assertions\n",
            solution_code="def clamp(x: int) -> int:\n    return 0 if x < 0 else 10 if x > 10 else x\n\nassert clamp(-1) == 0\nassert clamp(0) == 0\nassert clamp(10) == 10\nassert clamp(11) == 10\nprint('boundary-ok')",
            expected_output="boundary-ok",
            tags=["testing", "boundaries", "advanced"],
            time_estimate_mins=14,
        ),
        _q(
            title="Minimal Test Runner",
            slug="py-test-mini-runner",
            difficulty="advanced",
            task="Build a tiny test runner over two test functions and print passed count.",
            starter_code="# implement mini test runner\n",
            solution_code="def test_one():\n    assert 1 + 1 == 2\n\ndef test_two():\n    assert 'a'.upper() == 'A'\n\ntests = [test_one, test_two]\npassed = 0\nfor t in tests:\n    t()\n    passed += 1\nprint(passed)",
            expected_output="2",
            tags=["testing", "runner", "advanced"],
            time_estimate_mins=14,
        ),
        _q(
            title="Contract Test for Interface",
            slug="py-test-contract-interface",
            difficulty="advanced",
            task="Define two classes with same `get()` contract and assert both return expected values.",
            starter_code="# write contract assertions for two implementations\n",
            solution_code="class A:\n    def get(self) -> int:\n        return 1\n\nclass B:\n    def get(self) -> int:\n        return 1\n\nfor impl in (A(), B()):\n    assert impl.get() == 1\nprint('contract-ok')",
            expected_output="contract-ok",
            tags=["testing", "contract", "advanced"],
        ),
        _q(
            title="Retry Logic Test with Stub",
            slug="py-test-retry-logic-stub",
            difficulty="advanced",
            task="Test retry logic with a stub that fails once then succeeds, then print total attempts.",
            starter_code="# implement stub and retry_once helper, then print attempts\n",
            solution_code="attempts = {'n': 0}\n\ndef flaky():\n    attempts['n'] += 1\n    if attempts['n'] == 1:\n        raise RuntimeError('first fail')\n    return 'ok'\n\ndef retry_once(fn):\n    try:\n        return fn()\n    except RuntimeError:\n        return fn()\n\nassert retry_once(flaky) == 'ok'\nprint(attempts['n'])",
            expected_output="2",
            tags=["testing", "retry", "advanced"],
            time_estimate_mins=14,
        ),
    ]


def _stdlib_questions() -> list[dict]:
    return [
        _q(
            title="math.sqrt Usage",
            slug="py-std-math-sqrt",
            difficulty="basic",
            task="Import `math` and print `math.sqrt(81)` as int.",
            starter_code="import math\n# print integer sqrt of 81\n",
            solution_code="import math\nprint(int(math.sqrt(81)))",
            expected_output="9",
            tags=["stdlib", "math"],
        ),
        _q(
            title="random Seed Repeatability",
            slug="py-std-random-seed",
            difficulty="basic",
            task="Seed random with 7, generate `randint(1, 10)` twice after reseeding, print equality check.",
            starter_code="import random\n# show deterministic output by reseeding\n",
            solution_code="import random\nrandom.seed(7)\na = random.randint(1, 10)\nrandom.seed(7)\nb = random.randint(1, 10)\nprint(a == b)",
            expected_output="True",
            tags=["stdlib", "random"],
        ),
        _q(
            title="datetime Date Part",
            slug="py-std-datetime-year",
            difficulty="basic",
            task="Create date `datetime.date(2026, 1, 15)` and print its year.",
            starter_code="import datetime\n# create date and print year\n",
            solution_code="import datetime\nprint(datetime.date(2026, 1, 15).year)",
            expected_output="2026",
            tags=["stdlib", "datetime"],
        ),
        _q(
            title="timedelta Arithmetic",
            slug="py-std-timedelta-days",
            difficulty="basic",
            task="Add 5 days to `datetime.date(2026, 6, 1)` and print resulting day number.",
            starter_code="import datetime\n# add 5 days and print day\n",
            solution_code="import datetime\nstart = datetime.date(2026, 6, 1)\nprint((start + datetime.timedelta(days=5)).day)",
            expected_output="6",
            tags=["stdlib", "datetime"],
        ),
        _q(
            title="pathlib Name and Suffix",
            slug="py-std-pathlib-name-suffix",
            difficulty="basic",
            task="Use `Path('notes.txt')` and print `name` then `suffix` on separate lines.",
            starter_code="from pathlib import Path\n# print file name and suffix\n",
            solution_code="from pathlib import Path\np = Path('notes.txt')\nprint(p.name)\nprint(p.suffix)",
            expected_output="notes.txt\n.txt",
            tags=["stdlib", "pathlib"],
        ),
        _q(
            title="os.path join",
            slug="py-std-ospath-join",
            difficulty="basic",
            task="Use `os.path.join('data', 'train.csv')` and print the result.",
            starter_code="import os\n# join data and train.csv\n",
            solution_code="import os\nprint(os.path.join('data', 'train.csv'))",
            expected_output="data/train.csv",
            tags=["stdlib", "os.path"],
        ),
        _q(
            title="sys Platform Prefix",
            slug="py-std-sys-platform-prefix",
            difficulty="basic",
            task="Print whether `sys.platform` starts with `'win'` or `'linux'` or `'darwin'` by checking tuple membership.",
            starter_code="import sys\n# print check for known platform prefix\n",
            solution_code="import sys\nprint(sys.platform.startswith(('win', 'linux', 'darwin')))",
            expected_output="True",
            tags=["stdlib", "sys"],
        ),
        _q(
            title="statistics Mean",
            slug="py-std-statistics-mean",
            difficulty="basic",
            task="Use `statistics.mean` on `[10, 20, 30]` and print as int.",
            starter_code="import statistics\n# print mean\n",
            solution_code="import statistics\nprint(int(statistics.mean([10, 20, 30])))",
            expected_output="20",
            tags=["stdlib", "statistics"],
        ),
        _q(
            title="decimal Exact Sum",
            slug="py-std-decimal-exact-sum",
            difficulty="basic",
            task="Use `Decimal` to add `'0.1'` and `'0.2'`, print the exact string result.",
            starter_code="from decimal import Decimal\n# print Decimal sum of 0.1 and 0.2\n",
            solution_code="from decimal import Decimal\nprint(Decimal('0.1') + Decimal('0.2'))",
            expected_output="0.3",
            tags=["stdlib", "decimal"],
        ),
        _q(
            title="fractions Simplify",
            slug="py-std-fractions-simplify",
            difficulty="basic",
            task="Create `Fraction(8, 12)` and print it.",
            starter_code="from fractions import Fraction\n# print simplified fraction\n",
            solution_code="from fractions import Fraction\nprint(Fraction(8, 12))",
            expected_output="2/3",
            tags=["stdlib", "fractions"],
        ),
        _q(
            title="Counter Most Common",
            slug="py-std-counter-most-common",
            difficulty="intermediate",
            task="Use `Counter('banana')` and print the top character tuple from `.most_common(1)[0]`.",
            starter_code="from collections import Counter\n# print most common char tuple\n",
            solution_code="from collections import Counter\nprint(Counter('banana').most_common(1)[0])",
            expected_output="('a', 3)",
            tags=["stdlib", "collections", "counter"],
        ),
        _q(
            title="defaultdict Grouping",
            slug="py-std-defaultdict-group",
            difficulty="intermediate",
            task="Group pairs `[('a',1), ('a',2), ('b',3)]` into `defaultdict(list)` and print dict form.",
            starter_code="from collections import defaultdict\npairs = [('a', 1), ('a', 2), ('b', 3)]\n# group by key\n",
            solution_code="from collections import defaultdict\npairs = [('a', 1), ('a', 2), ('b', 3)]\ng = defaultdict(list)\nfor k, v in pairs:\n    g[k].append(v)\nprint(dict(g))",
            expected_output="{'a': [1, 2], 'b': [3]}",
            tags=["stdlib", "collections", "defaultdict"],
        ),
        _q(
            title="deque Rotation",
            slug="py-std-deque-rotation",
            difficulty="intermediate",
            task="Rotate `deque([1,2,3,4])` by 1 and print as list.",
            starter_code="from collections import deque\n# rotate deque and print list\n",
            solution_code="from collections import deque\nd = deque([1, 2, 3, 4])\nd.rotate(1)\nprint(list(d))",
            expected_output="[4, 1, 2, 3]",
            tags=["stdlib", "collections", "deque"],
        ),
        _q(
            title="itertools Combinations",
            slug="py-std-itertools-combinations",
            difficulty="intermediate",
            task="Print number of 2-combinations from `['a','b','c','d']`.",
            starter_code="from itertools import combinations\n# print count of combinations\n",
            solution_code="from itertools import combinations\nprint(len(list(combinations(['a', 'b', 'c', 'd'], 2))))",
            expected_output="6",
            tags=["stdlib", "itertools"],
        ),
        _q(
            title="itertools Chain",
            slug="py-std-itertools-chain",
            difficulty="intermediate",
            task="Use `chain([1,2], [3,4])` and print list.",
            starter_code="from itertools import chain\n# print chained list\n",
            solution_code="from itertools import chain\nprint(list(chain([1, 2], [3, 4])))",
            expected_output="[1, 2, 3, 4]",
            tags=["stdlib", "itertools"],
        ),
        _q(
            title="functools lru_cache",
            slug="py-std-functools-lru-cache",
            difficulty="intermediate",
            task="Decorate Fibonacci with `lru_cache` and print `fib(8)`.",
            starter_code="from functools import lru_cache\n# define cached fib and print fib(8)\n",
            solution_code="from functools import lru_cache\n\n@lru_cache(maxsize=None)\ndef fib(n: int) -> int:\n    return n if n < 2 else fib(n - 1) + fib(n - 2)\n\nprint(fib(8))",
            expected_output="21",
            tags=["stdlib", "functools", "cache"],
        ),
        _q(
            title="json Dumps Sort Keys",
            slug="py-std-json-dumps-sorted",
            difficulty="intermediate",
            task="Dump `{'b':2, 'a':1}` with `sort_keys=True` and print resulting JSON string.",
            starter_code="import json\n# print sorted JSON dump\n",
            solution_code="import json\nprint(json.dumps({'b': 2, 'a': 1}, sort_keys=True))",
            expected_output="{\"a\": 1, \"b\": 2}",
            tags=["stdlib", "json"],
        ),
        _q(
            title="csv Reader from StringIO",
            slug="py-std-csv-stringio",
            difficulty="intermediate",
            task="Use `csv.reader` over `'x,y\\n1,2\\n'` via `StringIO` and print second row.",
            starter_code="import csv\nfrom io import StringIO\n# read CSV rows and print second row\n",
            solution_code="import csv\nfrom io import StringIO\nrows = list(csv.reader(StringIO('x,y\\n1,2\\n')))\nprint(rows[1])",
            expected_output="['1', '2']",
            tags=["stdlib", "csv", "io"],
        ),
        _q(
            title="re Findall Digits",
            slug="py-std-re-findall-digits",
            difficulty="intermediate",
            task="Use regex `\\d+` to find numbers in `'v2 build 17'` and print list.",
            starter_code="import re\n# find all number substrings\n",
            solution_code="import re\nprint(re.findall(r'\\d+', 'v2 build 17'))",
            expected_output="['2', '17']",
            tags=["stdlib", "re"],
        ),
        _q(
            title="pathlib Parts",
            slug="py-std-pathlib-parts",
            difficulty="intermediate",
            task="Print number of parts in `Path('a/b/c.txt')`.",
            starter_code="from pathlib import Path\n# print part count\n",
            solution_code="from pathlib import Path\nprint(len(Path('a/b/c.txt').parts))",
            expected_output="3",
            tags=["stdlib", "pathlib"],
        ),
        _q(
            title="Dataclass Ordering",
            slug="py-std-dataclass-ordering",
            difficulty="advanced",
            task="Create ordered dataclass `Point(x, y)`, compare `Point(1,2) < Point(2,1)`, print result.",
            starter_code="from dataclasses import dataclass\n# define ordered dataclass and compare two points\n",
            solution_code="from dataclasses import dataclass\n\n@dataclass(order=True)\nclass Point:\n    x: int\n    y: int\n\nprint(Point(1, 2) < Point(2, 1))",
            expected_output="True",
            tags=["stdlib", "dataclasses", "advanced"],
        ),
        _q(
            title="Enum Value Access",
            slug="py-std-enum-value",
            difficulty="advanced",
            task="Define enum `Status` with `OK=200`, print `Status.OK.value`.",
            starter_code="from enum import Enum\n# define Status enum and print OK value\n",
            solution_code="from enum import Enum\n\nclass Status(Enum):\n    OK = 200\n\nprint(Status.OK.value)",
            expected_output="200",
            tags=["stdlib", "enum", "advanced"],
        ),
        _q(
            title="contextlib suppress",
            slug="py-std-contextlib-suppress",
            difficulty="advanced",
            task="Use `contextlib.suppress(ZeroDivisionError)` around `1/0`, then print `'continued'`.",
            starter_code="from contextlib import suppress\n# suppress ZeroDivisionError and continue\n",
            solution_code="from contextlib import suppress\n\nwith suppress(ZeroDivisionError):\n    1 / 0\nprint('continued')",
            expected_output="continued",
            tags=["stdlib", "contextlib", "advanced"],
        ),
        _q(
            title="inspect Signature Parameters",
            slug="py-std-inspect-signature",
            difficulty="advanced",
            task="Use `inspect.signature` on `def f(a, b=1): ...` and print parameter count.",
            starter_code="import inspect\n# define function and print signature parameter count\n",
            solution_code="import inspect\n\ndef f(a, b=1):\n    return a + b\n\nprint(len(inspect.signature(f).parameters))",
            expected_output="2",
            tags=["stdlib", "inspect", "advanced"],
        ),
        _q(
            title="ast Node Type",
            slug="py-std-ast-node-type",
            difficulty="advanced",
            task="Parse expression `'x + 1'` with `ast.parse(..., mode='eval')` and print body node type name.",
            starter_code="import ast\n# parse expression and print body node type\n",
            solution_code="import ast\ntree = ast.parse('x + 1', mode='eval')\nprint(type(tree.body).__name__)",
            expected_output="BinOp",
            tags=["stdlib", "ast", "advanced"],
        ),
        _q(
            title="dis Bytecode Contains",
            slug="py-std-dis-bytecode",
            difficulty="advanced",
            task="Disassemble `def add(a,b): return a+b` and print whether `'BINARY_OP'` appears.",
            starter_code="import dis\nimport io\n# disassemble and check for BINARY_OP\n",
            solution_code="import dis\nimport io\n\ndef add(a, b):\n    return a + b\n\nbuf = io.StringIO()\ndis.dis(add, file=buf)\nprint('BINARY_OP' in buf.getvalue())",
            expected_output="True",
            tags=["stdlib", "dis", "advanced"],
        ),
        _q(
            title="weakref Reference Life",
            slug="py-std-weakref-lifecycle",
            difficulty="advanced",
            task="Create object, weakref it, delete strong reference, run gc, and print whether weakref is None.",
            starter_code="import gc\nimport weakref\n# build weak reference lifecycle check\n",
            solution_code="import gc\nimport weakref\n\nclass Box:\n    pass\n\nobj = Box()\nref = weakref.ref(obj)\ndel obj\ngc.collect()\nprint(ref() is None)",
            expected_output="True",
            tags=["stdlib", "weakref", "gc", "advanced"],
            time_estimate_mins=14,
        ),
        _q(
            title="heapq Smallest Items",
            slug="py-std-heapq-nsmallest",
            difficulty="advanced",
            task="Use `heapq.nsmallest(3, [9,1,8,2,7])` and print the list.",
            starter_code="import heapq\n# print three smallest values\n",
            solution_code="import heapq\nprint(heapq.nsmallest(3, [9, 1, 8, 2, 7]))",
            expected_output="[1, 2, 7]",
            tags=["stdlib", "heapq", "advanced"],
        ),
    ]


QUESTIONS_BY_TOPIC: dict[str, list[dict]] = {
    "functional": _functional_questions(),
    "comprehensions": _comprehension_questions(),
    "type-hints": _type_hint_questions(),
    "testing": _testing_questions(),
    "stdlib": _stdlib_questions(),
}

MODULE_LABELS = {
    "functional": "Module 16 — Functional Programming",
    "comprehensions": "Module 17 — Comprehensions & Expressions",
    "type-hints": "Module 18 — Type Hints & Static Typing",
    "testing": "Module 19 — Testing with pytest",
    "stdlib": "Module 20 — Standard Library Deep Dive",
}

EXPECTED_COUNTS = {
    "functional": {"basic": 8, "intermediate": 8, "advanced": 6},
    "comprehensions": {"basic": 10, "intermediate": 8, "advanced": 6},
    "type-hints": {"basic": 8, "intermediate": 10, "advanced": 8},
    "testing": {"basic": 8, "intermediate": 10, "advanced": 8},
    "stdlib": {"basic": 10, "intermediate": 10, "advanced": 8},
}


def _validate_distribution() -> None:
    for topic_slug, expected in EXPECTED_COUNTS.items():
        questions = QUESTIONS_BY_TOPIC[topic_slug]
        counter = Counter(q["difficulty"] for q in questions)
        if dict(counter) != expected:
            raise ValueError(
                f"Distribution mismatch for {topic_slug}: got {dict(counter)}, expected {expected}"
            )
        if any(not q["slug"].startswith("py-") for q in questions):
            raise ValueError(f"All slugs for {topic_slug} must start with 'py-'")


async def main() -> None:
    _validate_distribution()
    total = 0
    for topic_slug in ["functional", "comprehensions", "type-hints", "testing", "stdlib"]:
        seeded = await seed_questions_for_topic(
            topic_slug,
            QUESTIONS_BY_TOPIC[topic_slug],
            MODULE_LABELS[topic_slug],
        )
        total += seeded
    print(f"Seeded {total} questions across modules 16-20")


if __name__ == "__main__":
    asyncio.run(main())
